"""land_review -- SubagentStop: land an experiment-reviewer's verdict as a file.

Plan section 8 and docs/protocol.md section 5 (the grader rule): experiment-reviewer is
read-only, so its verdict reaches the notebook through this hook, never through its own
writes or an MCP write tool.

Scope: the stopping agent is ``experiment-reviewer`` (namespace stripped), and the
session's cwd lies in a Researcher home (``_researcher.researcher_home``). Silent
otherwise.

The report's ``## Review record`` block (agents/experiment-reviewer.md) is parsed:
Subject, Run (A|B), Verdict, Result, Commit, Validation, Outcome, Model, Reproduction,
Ticket. The file written is

    <home>/<paths.audits>/<subject slug>/<YYYY-MM-DD>-<A|B>.md      (-2, -3 ... if taken)

with the parsed fields as frontmatter, a generated-by-academy marker (so
generated_view_guard refuses hand edits: a verdict is never rewritten) and the report
verbatim below.

* **Model.** Taken from the subagent's transcript when it names one, else from the
  report, and recorded on every verdict: ``model`` is the roster label (``fable``,
  ``opus-5.5``, or the family of any other model) and ``model_id`` the name as given.
  The primaries are Fable and Opus 5.5, equal in authority (``rs.PRIMARY_MODELS``); a
  positive verdict (SOUND / SOUND MODULO) reached on any other model (Sonnet, Haiku, an
  older Opus) is recorded as ``verdict: GAP`` with ``capped: true`` and the original in
  ``verdict_given`` (roster-rules.md, model fallback: a degraded verdict never counts).
* **Malformed report.** The first time, the stop is blocked with the list of problems,
  so the reviewer restates its record block. If it stops again still malformed
  (``stop_hook_active``), the report is kept under ``<audits>/_unparsed/`` and nothing
  counts as a verdict.
"""

import json
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)

import _academy as ac  # noqa: E402
import _researcher as rs  # noqa: E402

AGENT = "experiment-reviewer"
MARKER = "# generated by academy: researcher land_review.py; do not edit"


def _text_of(message):
    content = message.get("content") if isinstance(message, dict) else None
    if isinstance(content, str):
        return content
    if isinstance(content, list):
        return "\n".join(c.get("text", "") for c in content
                         if isinstance(c, dict) and c.get("type") == "text")
    return ""


def transcript_last(path):
    """``(text, model)`` of the last assistant message with text in a JSONL transcript."""
    text, model = "", ""
    if not path or not os.path.isfile(path):
        return text, model
    try:
        with open(path, "r", encoding="utf-8", errors="replace") as fh:
            for line in fh:
                try:
                    rec = json.loads(line)
                except ValueError:
                    continue
                if not isinstance(rec, dict) or rec.get("type") != "assistant":
                    continue
                msg = rec.get("message") or {}
                t = _text_of(msg)
                if t.strip():
                    text = t
                if isinstance(msg, dict) and msg.get("model"):
                    model = str(msg["model"])
    except OSError:
        pass
    return text, model


def model_family(name):
    """The roster label of ``name`` (``rs.model_label``), 'unknown' when empty."""
    return rs.model_label(name) or "unknown"


def _unique(folder, stem):
    path = os.path.join(folder, stem + ".md")
    n = 2
    while os.path.exists(path):
        path = os.path.join(folder, "%s-%d.md" % (stem, n))
        n += 1
    return path


def render(meta, report):
    text = ac.write_frontmatter(meta, "\n" + report.strip() + "\n")
    return text.replace("---\n", "---\n%s\n" % MARKER, 1)


def land(event, ws=None, date=None):
    """Handle one SubagentStop event; returns ``(action, detail)``.

    action: None (silent), 'block' (detail = reason), 'landed' / 'unparsed' (detail = path).
    """
    _, bare = ac.agent_identity(event)
    if bare != AGENT:
        return None, ""
    home, cfg, instance = rs.researcher_home(ac.event_cwd(event), ws)
    if not home:
        return None, ""
    audits = rs.notebook_paths(home, cfg)["audits"]
    t_text, t_model = transcript_last(event.get("agent_transcript_path")
                                      or event.get("transcript_path"))
    report = event.get("last_assistant_message")
    report = report if isinstance(report, str) and report.strip() else t_text
    fields, probs = rs.parse_review(report)
    date = date or ac.today()
    if probs:
        if not event.get("stop_hook_active"):
            return "block", (
                "land_review: your report cannot be landed as a verdict (%s). End with a "
                "'## Review record' block exactly as agents/experiment-reviewer.md gives it: "
                "Subject, Run, Verdict, Result, Commit, Validation, Outcome, Model, "
                "Reproduction, Ticket, one '- Key: value' line each." % "; ".join(probs))
        folder = os.path.join(audits, "_unparsed")
        path = _unique(folder, "%s-%s" % (date, ac.slugify(event.get("agent_id") or "run",
                                                           maxlen=20)))
        meta = {"subject": fields.get("subject") or None, "problems": probs,
                "landed": date, "landed_by": "researcher/land_review"}
        ac.atomic_write(path, render(meta, report or "(empty report)"))
        return "unparsed", path
    model_id = str(t_model or fields.get("model") or "").strip()
    model = model_family(model_id)
    given = fields["verdict"]
    capped = not rs.is_primary(model_id) and given in rs.POSITIVE
    slug = rs.subject_slug(fields["subject"])
    folder = os.path.join(audits, slug)
    path = _unique(folder, "%s-%s" % (date, fields["run"]))
    run_id = event.get("agent_id") or os.path.splitext(os.path.basename(path))[0]
    meta = {
        "subject": fields["subject"],
        "run": fields["run"],
        "run_id": "%s" % run_id,
        "verdict": "GAP" if capped else given,
        "verdict_given": given,
        "assumption": fields.get("assumption") or None,
        "capped": capped,
        "model": model,
        "model_id": model_id or None,
        "result": fields.get("result") or None,
        "commit": fields.get("commit") or None,
        "validation": fields.get("validation"),
        "outcome": fields.get("outcome"),
        "reproduction": fields.get("reproduction") or None,
        "ticket": fields.get("ticket") or None,
        "instance": instance,
        "landed": date,
        "landed_by": "researcher/land_review",
    }
    ac.atomic_write(path, render(meta, report))
    return "landed", path


def main():
    event = ac.read_event()
    try:
        action, detail = land(event)
    except Exception as exc:          # never trap the agent because of a hook bug
        sys.stderr.write("land_review: %s\n" % exc)
        return 0
    if action == "block":
        ac.emit_block(detail)
    elif action in ("landed", "unparsed"):
        ac.emit({"systemMessage": "researcher: experiment review %s at %s"
                 % ("landed" if action == "landed" else "kept UNPARSED", detail)})
    return 0


if __name__ == "__main__":
    sys.exit(main())
