"""settle.py -- settle a returned result that reports candidate counterexamples.

Port of the first notebook's ``settle-candidates`` workflow into a tested script (plan
section 3.6). The model-side work is split by role:

* the **script audit** is the experiment-review pair (``reviews.py``: two
  experiment-reviewer runs, B only after a positive A), landed by ``land_review.py``;
* each **candidate** is a statement "this member is a counterexample to <claim>", so it
  is a proof review: one ``verify`` ticket per candidate to the Expert, whose
  review-chair runs the rigor-reviewer pair (A, then B only if A is positive) and
  returns CONFIRMED / PLAUSIBLE / GAP / DISPROVED. The verdicts are collected into the
  candidates file below.

This script decides; it launches nothing and files nothing.

Usage (from a Researcher home, or with --home):

    py settle.py plan   SUBJECT --candidates FILE [--max N] [--json]
    py settle.py decide SUBJECT --candidates FILE [--json]
    py settle.py record SUBJECT --candidates FILE [--partial]

The candidates file is JSON, a list (or {"candidates": [...]}) of objects:

    {"name": "member-7", "rank": 1, "ref": "lab:hunt-x#member-7",
     "detail": "free text from the report (parameters, certificate)",
     "ticket": "T-0042",                 # the verify ticket, once filed
     "verdicts": [{"run": "A", "verdict": "CONFIRMED", "model": "fable",
                   "run_id": "rv-...", "packet": "P-0051"}, ...]}

``rank`` orders candidates by likelihood (1 first). At most ``--max`` (default
``budget.itemsPerRun``, never more than 3) candidates are filed per run; the rest are
reported as deferred.

Candidate decisions (a run on a model other than Fable counts as not positive):

    no verdicts                          PENDING (file the verify ticket)
    run A not CONFIRMED                  NOT CLEARED (run B not dispatched)
    run A CONFIRMED, no run B            PENDING (run B)
    both CONFIRMED                       REFUTATION CLEARED
    A and B differ                       UNRESOLVED (verifiers disagree)
    otherwise                            NOT CLEARED

A candidate is **recordable** only when the script audit cleared (cleared or
cleared-modulo) **and** its own pair cleared. Nothing else is recordable, whatever its
verdicts. ``record`` writes the decision record ``<audits>/<slug>/<date>-settle.md``
(generated marker; never rewritten, a new record gets a new file).
"""

import argparse
import json
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)

import _academy as ac  # noqa: E402
import _researcher as rs  # noqa: E402
import reviews  # noqa: E402

PROOF_VERDICTS = ("CONFIRMED", "PLAUSIBLE", "GAP", "DISPROVED")
PRIMARY = "fable"
MARKER = "# generated by academy: researcher settle.py; do not edit"


def _verdict(v):
    s = " ".join(str(v.get("verdict") or "").replace("_", " ").split()).upper()
    return s if s in PROOF_VERDICTS else ""


def _primary(v):
    return PRIMARY in str(v.get("model") or PRIMARY).lower() and not v.get("fallback")


def _positive(v):
    return _verdict(v) == "CONFIRMED" and _primary(v)


def load_candidates(path):
    with open(path, "r", encoding="utf-8-sig") as fh:
        data = json.load(fh)
    if isinstance(data, dict):
        data = data.get("candidates", [])
    if not isinstance(data, list) or not all(isinstance(c, dict) for c in data):
        raise ac.AcademyError("candidates must be a list of objects")
    for i, c in enumerate(data):
        if not c.get("name"):
            raise ac.AcademyError("candidate %d has no name" % (i + 1))
    return sorted(data, key=lambda c: (c.get("rank") if isinstance(c.get("rank"), int)
                                       else 10 ** 6, c["name"]))


def decide_candidate(c):
    """The decision for one candidate, from its verdicts (ported from the JS pipeline)."""
    runs = [v for v in (c.get("verdicts") or []) if isinstance(v, dict)]
    a = next((v for v in runs if str(v.get("run")).upper() == "A"), None)
    b = next((v for v in runs if str(v.get("run")).upper() == "B"), None)
    label = lambda v: _verdict(v) + ("" if _primary(v) else " (fallback)")  # noqa: E731
    if a is None:
        return "PENDING", "no verdicts yet: file (or wait for) the verify ticket"
    if not _positive(a):
        return "NOT CLEARED", "run A: %s; run B not dispatched" % (label(a) or a.get("verdict"))
    if b is None:
        return "PENDING", "run A CONFIRMED; waiting for run B"
    if _positive(b):
        return "REFUTATION CLEARED", "both runs CONFIRMED on the primary model"
    if _verdict(a) != _verdict(b):
        return "UNRESOLVED", "verifiers disagree: A %s, B %s" % (label(a), label(b))
    return "NOT CLEARED", "run B: %s" % label(b)


def _max_items(home, want=None):
    _, cfg, _ = rs.researcher_home(home)
    n = ((cfg or {}).get("budget") or {}).get("itemsPerRun", 3)
    n = min(int(n), 3)
    return max(1, min(want, n)) if want else n


def plan(audit, cands, max_items):
    """Which candidates get a verify ticket now, which wait, which are deferred."""
    file_now, waiting, deferred, done = [], [], [], []
    for c in cands:
        state, _ = decide_candidate(c)
        if state != "PENDING":
            done.append(c["name"])
        elif c.get("ticket"):
            waiting.append(c["name"])
        elif len(file_now) + len(waiting) < max_items:
            file_now.append(c["name"])
        else:
            deferred.append(c["name"])
    notes = []
    if audit["state"] in ("need-A", "need-B"):
        notes.append("the script audit is not finished (%s): %s"
                     % (audit["state"], audit["next"]))
    elif audit["state"] not in ("cleared", "cleared-modulo"):
        notes.append("the script audit did not clear (%s): no candidate from this result "
                     "can be recorded; filing verify tickets would spend budget for nothing"
                     % audit["state"])
        deferred = file_now + deferred
        file_now = []
    return {"audit": audit["state"], "file_now": file_now, "waiting": waiting,
            "deferred": deferred, "decided": done, "max": max_items, "notes": notes}


def decide(audit, cands):
    rows = []
    for c in cands:
        state, why = decide_candidate(c)
        rows.append({"name": c["name"], "ref": c.get("ref"), "ticket": c.get("ticket"),
                     "decision": state, "why": why,
                     "verdicts": [_verdict(v) for v in c.get("verdicts") or []]})
    audit_ok = audit["state"] in ("cleared", "cleared-modulo")
    recordable = [r["name"] for r in rows if audit_ok and r["decision"] == "REFUTATION CLEARED"]
    if not audit_ok:
        note = ("Nothing is recordable: the script audit is %s, so no candidate from this "
                "result may be recorded regardless of its verdicts." % audit["state"])
    elif recordable:
        note = ("Recordable: two CONFIRMED verdicts each and a cleared audit. claim-keeper "
                "records each as a refutation (claims_set_status with the proof grounds); "
                "everything else stays uncited.")
    else:
        note = ("The audit cleared but no candidate did. A cleared audit with no candidates "
                "left standing is quotable only as 'no counterexample over the class', with "
                "the class's exclusions.")
    return {"audit": {k: audit[k] for k in ("state", "a", "b", "verdicts", "reasons",
                                            "assumptions", "proposed_status")},
            "candidates": rows, "recordable": recordable, "note": note}


def render_record(subject, result, date):
    lines = ["---", MARKER, "subject: %s" % subject, "kind: settle", "date: %s" % date,
             "audit: %s" % result["audit"]["state"],
             "recordable: [%s]" % ", ".join(result["recordable"]), "---", "",
             "# Settle record: %s" % subject, "", "## Script audit", ""]
    au = result["audit"]
    lines.append("- State: %s; verdicts: %s" % (au["state"], ", ".join(au["verdicts"]) or "none"))
    for p in (au["a"], au["b"]):
        if p:
            lines.append("- Run file: `%s`" % p)
    for r in au["reasons"]:
        lines.append("- %s" % r)
    for a in au["assumptions"]:
        lines.append("- Modulo: %s" % a)
    lines += ["", "## Candidates", "", "| Candidate | Ticket | Verdicts | Decision | Why |",
              "|---|---|---|---|---|"]
    for r in result["candidates"]:
        lines.append("| %s | %s | %s | %s | %s |" % (r["name"], r["ticket"] or "",
                                                     " / ".join(r["verdicts"]) or "-",
                                                     r["decision"], r["why"]))
    if not result["candidates"]:
        lines.append("| (none) | | | | |")
    lines += ["", "## Decision", "", result["note"], ""]
    return "\n".join(lines)


def main(argv=None):
    ap = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    ap.add_argument("--home")
    sub = ap.add_subparsers(dest="cmd", required=True)
    for name in ("plan", "decide", "record"):
        p = sub.add_parser(name)
        p.add_argument("subject")
        p.add_argument("--candidates", help="candidates JSON (omit: no candidates)")
        p.add_argument("--json", action="store_true")
        if name == "plan":
            p.add_argument("--max", type=int)
        if name == "record":
            p.add_argument("--partial", action="store_true",
                           help="record even though the audit pair is unfinished")
            p.add_argument("--date")
    args = ap.parse_args(argv)
    try:
        home = args.home or os.getcwd()
        audits = reviews.audits_dir(home)
        audit = reviews.decide(reviews.load_runs(audits, args.subject))
        cands = load_candidates(args.candidates) if args.candidates else []
        if args.cmd == "plan":
            out = plan(audit, cands, _max_items(home, args.max))
            if args.json:
                print(json.dumps(out, indent=1))
            else:
                print("audit: %s; file now: %s; waiting: %s; deferred: %s"
                      % (out["audit"], ", ".join(out["file_now"]) or "-",
                         ", ".join(out["waiting"]) or "-", ", ".join(out["deferred"]) or "-"))
                for n in out["notes"]:
                    print("  - %s" % n)
            return 0
        result = decide(audit, cands)
        if args.cmd == "decide":
            if args.json:
                print(json.dumps(result, indent=1))
            else:
                print("audit: %s" % result["audit"]["state"])
                for r in result["candidates"]:
                    print("  %-24s %-20s %s" % (r["name"], r["decision"], r["why"]))
                print(result["note"])
            return 0
        if audit["state"] in ("need-A", "need-B") and not args.partial:
            raise ac.AcademyError("the audit pair is unfinished (%s); finish it or pass "
                                  "--partial" % audit["state"])
        folder = os.path.join(audits, rs.subject_slug(args.subject))
        date = args.date or ac.today()
        path = os.path.join(folder, "%s-settle.md" % date)
        n = 2
        while os.path.exists(path):
            path = os.path.join(folder, "%s-settle-%d.md" % (date, n))
            n += 1
        ac.atomic_write(path, render_record(args.subject, result, date))
        print(path.replace("\\", "/"))
        return 0
    except (ac.AcademyError, OSError, ValueError) as exc:
        sys.stderr.write("settle.py: %s\n" % exc)
        return 2


if __name__ == "__main__":
    sys.exit(main())
