"""land_review (SubagentStop hook), reviews.py (the pair's decision table) and settle.py."""

import json
import os
import unittest

from _fixtures import Workspace, write
import _academy as ac  # noqa: E402
import _researcher as rs  # noqa: E402
import land_review  # noqa: E402
import reviews  # noqa: E402
import settle  # noqa: E402


def report(run="A", verdict="SOUND", subject="lab:ew-check", commit="abc123",
           validation="passed", outcome="supports", model="claude-fable-5-1"):
    return ("The check is not a shadow: a false claim would fail the validation case.\n\n"
            "## Review record\n- Subject: %s\n- Run: %s\n- Verdict: %s\n- Result: results/x.json\n"
            "- Commit: %s\n- Validation: %s\n- Outcome: %s\n- Model: %s\n"
            "- Reproduction: none\n- Ticket: T-0003\n"
            % (subject, run, verdict, commit, validation, outcome, model))


class LandReviewTests(Workspace):
    def event(self, text, agent="researcher:experiment-reviewer", cwd=None, **extra):
        ev = {"hook_event_name": "SubagentStop", "agent_type": agent, "agent_id": "ag-1",
              "cwd": cwd or self.R, "last_assistant_message": text}
        ev.update(extra)
        return ev

    def test_lands_a_parsed_report(self):
        action, path = land_review.land(self.event(report()), date="2026-09-28")
        self.assertEqual(action, "landed")
        self.assertTrue(path.replace("\\", "/").endswith("audits/ew-check/2026-09-28-A.md"))
        text = rs.read_text(path)
        meta, body = ac.read_frontmatter(text)
        self.assertEqual((meta["subject"], meta["run"], meta["verdict"], meta["capped"]),
                         ("lab:ew-check", "A", "SOUND", False))
        self.assertEqual(meta["run_id"], "ag-1")
        self.assertIn("generated by academy", "\n".join(text.split("\n")[:5]))
        self.assertIn("## Review record", body)

    def test_second_landing_same_day_gets_a_new_file(self):
        p1 = land_review.land(self.event(report()), date="2026-09-28")[1]
        p2 = land_review.land(self.event(report()), date="2026-09-28")[1]
        self.assertNotEqual(p1, p2)
        self.assertTrue(p2.endswith("2026-09-28-A-2.md"))

    def test_fallback_model_caps_a_positive_verdict(self):
        tr = write(os.path.join(self.tmp, "t.jsonl"), json.dumps(
            {"type": "assistant", "message": {"model": "claude-sonnet-4-5",
                                              "content": [{"type": "text", "text": "x"}]}}) + "\n")
        ev = self.event(report(model="fable"), agent_transcript_path=tr)
        action, path = land_review.land(ev, date="2026-09-28")
        meta, _ = ac.read_frontmatter(rs.read_text(path))
        self.assertEqual((meta["verdict"], meta["verdict_given"], meta["capped"], meta["model"],
                          meta["model_id"]),
                         ("GAP", "SOUND", True, "sonnet", "claude-sonnet-4-5"))

    def test_opus_55_is_an_equal_primary(self):
        tr = write(os.path.join(self.tmp, "t.jsonl"), json.dumps(
            {"type": "assistant", "message": {"model": "claude-opus-5-5",
                                              "content": [{"type": "text", "text": "x"}]}}) + "\n")
        ev = self.event(report(), agent_transcript_path=tr)
        action, path = land_review.land(ev, date="2026-09-28")
        meta, _ = ac.read_frontmatter(rs.read_text(path))
        self.assertEqual((meta["verdict"], meta["verdict_given"], meta["capped"], meta["model"],
                          meta["model_id"]),
                         ("SOUND", "SOUND", False, "opus-5.5", "claude-opus-5-5"))

    def test_older_opus_is_capped(self):
        action, path = land_review.land(self.event(report(model="claude-opus-4-1")),
                                        date="2026-09-28")
        meta, _ = ac.read_frontmatter(rs.read_text(path))
        self.assertEqual((meta["verdict"], meta["capped"], meta["model"]), ("GAP", True, "opus"))

    def test_primary_models(self):
        self.assertEqual(rs.PRIMARY_MODELS, ("fable", "opus-5.5"))
        for name, want in (("claude-fable-5-1", True), ("claude-opus-5-5[1m]", True),
                           ("Opus 5.5", True), ("opus", False), ("claude-opus-4-1", False),
                           ("claude-sonnet-4-5", False), ("claude-haiku-4-5", False),
                           ("", False)):
            with self.subTest(name=name):
                self.assertEqual(rs.is_primary(name), want)

    def test_report_taken_from_transcript_when_event_lacks_it(self):
        tr = write(os.path.join(self.tmp, "t.jsonl"), json.dumps(
            {"type": "assistant", "message": {"model": "claude-fable-5-1",
                                              "content": [{"type": "text", "text": report()}]}}) + "\n")
        ev = self.event("", agent_transcript_path=tr)
        self.assertEqual(land_review.land(ev)[0], "landed")

    def test_malformed_report_blocks_once_then_is_kept_unparsed(self):
        action, reason = land_review.land(self.event("I think it is fine."))
        self.assertEqual(action, "block")
        self.assertIn("Review record", reason)
        action, path = land_review.land(self.event("Still fine.", stop_hook_active=True))
        self.assertEqual(action, "unparsed")
        self.assertIn("_unparsed", path.replace("\\", "/"))

    def test_other_agents_and_other_homes_are_silent(self):
        self.assertEqual(land_review.land(self.event(report(), agent="expert:rigor-reviewer"))[0],
                         None)
        self.assertEqual(land_review.land(self.event(report(), agent=""))[0], None)
        self.assertEqual(land_review.land(self.event(report(), cwd=self.L))[0], None)

    def test_legacy_researcher_home_lands_under_default_audits(self):
        action, path = land_review.land(self.event(report(), cwd=self.O))
        self.assertEqual(action, "landed")
        self.assertTrue(path.replace("\\", "/").startswith(self.O + "/audits/ew-check/"))

    def test_hook_process_emits_system_message(self):
        rc, out = self.run_hook("land_review.py", self.event(report()))
        self.assertEqual(rc, 0)
        self.assertIn("landed", out["systemMessage"])
        rc, out = self.run_hook("land_review.py", self.event("no record"))
        self.assertEqual(out["decision"], "block")

    def test_parse_review_rules(self):
        f, p = rs.parse_review(report(verdict="SOUND MODULO the enumeration terminates"))
        self.assertEqual((f["verdict"], f["assumption"], p),
                         ("SOUND MODULO", "the enumeration terminates", []))
        f, p = rs.parse_review(report(verdict="SOUND MODULO"))
        self.assertTrue(any("assumption" in x for x in p))
        f, p = rs.parse_review(report(verdict="PROBABLY OK"))
        self.assertTrue(any("Verdict" in x for x in p))
        f, p = rs.parse_review(report(run="C"))
        self.assertTrue(any("Run" in x for x in p))


class PairDecisionTests(Workspace):
    def land(self, *args, date="2026-09-28", agent_id=None, **kw):
        ev = {"agent_type": "researcher:experiment-reviewer", "cwd": self.R,
              "agent_id": agent_id or "id-%s" % kw.get("run", "A"),
              "last_assistant_message": report(*args, **kw)}
        return land_review.land(ev, date=date)[1]

    def decide(self):
        audits = reviews.audits_dir(self.R)
        return reviews.decide(reviews.load_runs(audits, "lab:ew-check"))

    def test_need_a_then_need_b(self):
        self.assertEqual(self.decide()["state"], "need-A")
        self.land(run="A")
        self.assertEqual(self.decide()["state"], "need-B")

    def test_negative_a_ends_the_pair(self):
        self.land(run="A", verdict="GAP")
        d = self.decide()
        self.assertEqual(d["state"], "not-cleared")
        self.assertIn("run A", d["reasons"][0])

    def test_capped_a_ends_the_pair(self):
        self.land(run="A", model="opus")
        self.assertEqual(self.decide()["state"], "not-cleared")

    def test_two_sound_clear_with_grounds(self):
        self.land(run="A")
        self.land(run="B")
        d = self.decide()
        self.assertEqual((d["state"], d["proposed_status"], d["grounds_problems"]),
                         ("cleared", "supported", []))
        g = d["grounds"]
        self.assertEqual((g["basis"], g["commit"], g["validation_passed"], g["outcome"]),
                         ("computation", "abc123", True, "supports"))
        self.assertEqual(len({v["run_id"] for v in g["verdicts"]}), 2)

    def test_grounds_pass_the_servers_check(self):
        """The grounds object is the shape academy's check_grounds accepts."""
        import sys
        mcp = os.path.join(ac.repo_root(), "academy", "mcp")
        if not os.path.isfile(os.path.join(mcp, "tools", "claims.py")):
            self.skipTest("academy MCP not present")
        for p in (os.path.join(ac.repo_root(), "academy", "lib"), mcp):
            if p not in sys.path:
                sys.path.insert(0, p)
        try:
            from tools import claims as server_claims  # noqa: F401
        except Exception as exc:  # pragma: no cover
            self.skipTest("cannot import the MCP tools: %s" % exc)
        self.land(run="A", outcome="refutes")
        self.land(run="B", outcome="refutes")
        d = self.decide()
        ok, why = server_claims.check_grounds("refuted", d["grounds"])
        self.assertTrue(ok, why)
        ok, _ = server_claims.check_grounds("proved", d["grounds"])
        self.assertFalse(ok)

    def test_sound_modulo_pair_and_disagreement(self):
        self.land(run="A", verdict="SOUND MODULO X")
        self.land(run="B", verdict="SOUND MODULO X")
        d = self.decide()
        self.assertEqual((d["state"], d["assumptions"]), ("cleared-modulo", ["X", "X"]))
        self.land(run="A", date="2026-09-29")
        self.land(run="B", verdict="SOUND MODULO Y", date="2026-09-29")
        self.assertEqual(self.decide()["state"], "unresolved")

    def test_commit_mismatch_is_unresolved(self):
        self.land(run="A")
        self.land(run="B", commit="def456")
        d = self.decide()
        self.assertEqual(d["state"], "unresolved")
        self.assertTrue(any("commits" in r for r in d["reasons"]))

    def test_b_negative_and_new_round(self):
        self.land(run="A")
        self.land(run="B", verdict="BROKEN")
        self.assertEqual(self.decide()["state"], "not-cleared")
        self.land(run="A", date="2026-09-30")
        self.assertEqual(self.decide()["state"], "need-B")

    def test_grounds_problems_without_validation(self):
        self.land(run="A", validation="not run")
        self.land(run="B", validation="not run")
        d = self.decide()
        self.assertEqual(d["state"], "cleared")
        self.assertTrue(d["grounds_problems"])

    def test_pending_and_cli(self):
        self.land(run="A")
        self.assertEqual(reviews.pending(reviews.audits_dir(self.R)), ["lab:ew-check"])
        rc, out, _ = self.run_script("reviews.py", "decide", "lab:ew-check", "--json")
        self.assertEqual(rc, 0)
        self.assertEqual(json.loads(out)["state"], "need-B")
        rc, out, _ = self.run_script("reviews.py", "brief", "lab:ew-check", "--run", "B")
        self.assertIn("run B", out)


class SettleTests(Workspace):
    def cands(self, *verdict_lists):
        out = []
        for i, vs in enumerate(verdict_lists, 1):
            out.append({"name": "m%d" % i, "rank": i, "verdicts": [
                {"run": r, "verdict": v, "model": m} for r, v, m in vs]})
        return out

    def test_candidate_table(self):
        f = "fable"
        cases = [
            ([], "PENDING"),
            ([("A", "GAP", f)], "NOT CLEARED"),
            ([("A", "CONFIRMED", "opus")], "NOT CLEARED"),
            ([("A", "CONFIRMED", f)], "PENDING"),
            ([("A", "CONFIRMED", f), ("B", "CONFIRMED", f)], "REFUTATION CLEARED"),
            ([("A", "CONFIRMED", f), ("B", "GAP", f)], "UNRESOLVED"),
            ([("A", "CONFIRMED", f), ("B", "CONFIRMED", "opus")], "NOT CLEARED"),
            # Opus 5.5 is an equal primary; Sonnet and older Opus are fallbacks
            ([("A", "CONFIRMED", "claude-opus-5-5")], "PENDING"),
            ([("A", "CONFIRMED", "claude-opus-5-5"), ("B", "CONFIRMED", f)],
             "REFUTATION CLEARED"),
            ([("A", "CONFIRMED", "opus-5.5"), ("B", "CONFIRMED", "claude-opus-5-5")],
             "REFUTATION CLEARED"),
            ([("A", "CONFIRMED", "claude-sonnet-4-5")], "NOT CLEARED"),
            ([("A", "CONFIRMED", f), ("B", "CONFIRMED", "claude-sonnet-4-5")], "NOT CLEARED"),
            ([("A", "CONFIRMED", "claude-opus-4-1")], "NOT CLEARED"),
        ]
        for vs, want in cases:
            with self.subTest(vs=vs):
                c = self.cands(vs)[0]
                self.assertEqual(settle.decide_candidate(c)[0], want)

    def test_recordable_needs_a_cleared_audit(self):
        f = "fable"
        c = self.cands([("A", "CONFIRMED", f), ("B", "CONFIRMED", f)])
        self.assertEqual(settle.decide({"state": "not-cleared", "a": None, "b": None,
                                        "verdicts": [], "reasons": [], "assumptions": [],
                                        "proposed_status": None}, c)["recordable"], [])
        self.assertEqual(settle.decide({"state": "cleared", "a": "x", "b": "y",
                                        "verdicts": ["SOUND", "SOUND"], "reasons": [],
                                        "assumptions": [], "proposed_status": "supported"},
                                       c)["recordable"], ["m1"])

    def test_plan_caps_and_defers(self):
        audit = {"state": "cleared", "next": ""}
        c = self.cands([], [], [], [])
        c[0]["ticket"] = "T-0009"
        p = settle.plan(audit, c, 3)
        self.assertEqual((p["waiting"], p["file_now"], p["deferred"]),
                         (["m1"], ["m2", "m3"], ["m4"]))
        p = settle.plan({"state": "not-cleared", "next": ""}, c, 3)
        self.assertEqual(p["file_now"], [])

    def test_record_writes_a_marked_file(self):
        ev = {"agent_type": "experiment-reviewer", "cwd": self.R}
        for run in ("A", "B"):
            ev.update(agent_id=run, last_assistant_message=report(run=run))
            land_review.land(ev, date="2026-09-28")
        cf = write(os.path.join(self.tmp, "c.json"), json.dumps(self.cands(
            [("A", "CONFIRMED", "fable"), ("B", "CONFIRMED", "fable")])))
        rc, out, err = self.run_script("settle.py", "record", "lab:ew-check",
                                       "--candidates", cf, "--date", "2026-09-28")
        self.assertEqual(rc, 0, err)
        text = rs.read_text(out.strip())
        self.assertIn("generated by academy", "\n".join(text.split("\n")[:5]))
        self.assertIn("recordable: [m1]", text)
        # the settle record is not mistaken for a review run
        out = self.run_script("reviews.py", "decide", "lab:ew-check", "--json")[1]
        self.assertEqual(json.loads(out)["state"], "cleared")

    def test_record_refuses_an_unfinished_audit(self):
        rc, _, err = self.run_script("settle.py", "record", "lab:ew-check")
        self.assertEqual(rc, 2)
        self.assertIn("unfinished", err)


if __name__ == "__main__":
    unittest.main()
