"""PreToolUse hook on Edit|Write|MultiEdit: generated views are never edited by hand.

A file is a generated view (docs/protocol.md section 7) when
  * one of its first ``MARKER_LINES`` lines contains ``MARKER`` (case-insensitive), or
  * it lies in the current home and matches the home's ``paths.views`` in academy.json.
Either way the edit is denied, for every caller: the fix is to change the source and
rerun the generator.

The hook also guards the caller handshake directory (``caller_dir()``, see
docs/protocol.md section 1): an Edit/Write into it, or a Bash/PowerShell command
that names it, is denied, since a forged record would let an agent speak as another
caller. Shell writes to views and tickets are not parsed (best effort only; the
SessionStart reconcile and ticket_edit_check catch board damage afterwards).
Anything else passes silently.
"""

import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import _academy as ac  # noqa: E402

MARKER = "generated by academy"
MARKER_LINES = 5


def has_marker(path, lines=MARKER_LINES):
    """True when one of the first ``lines`` lines of ``path`` carries the marker."""
    try:
        with open(path, "r", encoding="utf-8", errors="replace") as fh:
            for _ in range(lines):
                ln = fh.readline()
                if not ln:
                    break
                if MARKER in ln.lower():
                    return True
    except OSError:
        return False
    return False


def _config_for(path):
    home = ac.find_home(path)
    if not home:
        return None
    try:
        return ac.load_config(home)
    except ac.AcademyError:
        return None


def _callers_markers():
    d = os.path.abspath(ac.caller_dir())
    return {d.lower(), d.replace("\\", "/").lower(), "academy/callers", "academy\\callers"}


def in_caller_dir(path):
    d = os.path.normcase(os.path.abspath(ac.caller_dir()))
    p = os.path.normcase(os.path.abspath(path))
    return p == d or p.startswith(d + os.sep)


def decide(event):
    """``None`` or ``("deny", reason)`` for one PreToolUse event."""
    cmd = ac.shell_command(event)
    if cmd and ac.tool_name(event) in ("Bash", "PowerShell"):
        low = cmd.lower()
        if any(m in low for m in _callers_markers()):
            return ("deny", "academy: the caller handshake directory is written only by "
                            "the mcp_write_gate hook (docs/protocol.md section 1).")
        return None
    path = ac.edited_path(event)
    if not path:
        return None
    if not os.path.isabs(path):
        path = os.path.join(ac.event_cwd(event), path)
    if in_caller_dir(path):
        return ("deny", "academy: %s is in the caller handshake directory, which only the "
                        "mcp_write_gate hook writes (docs/protocol.md section 1)." % path)
    if os.path.isfile(path) and has_marker(path):
        return ("deny", "academy: %s is a generated view (its header says '%s'). "
                        "Change its source and rerun the generator instead."
                % (path, MARKER))
    cfg = _config_for(path)
    if cfg and ac.path_in_role(path, cfg, "views"):
        return ("deny", "academy: %s is listed under paths.views in %s/.claude/academy.json, "
                        "so it is generated. Change its source and rerun the generator "
                        "instead." % (path, cfg["_home"]))
    return None


def main():
    try:
        sys.stdout.reconfigure(encoding="utf-8")
    except (AttributeError, ValueError):
        pass
    verdict = decide(ac.read_event())
    if verdict:
        ac.emit_permission(verdict[0], verdict[1])
    return 0


if __name__ == "__main__":
    sys.exit(main())
