"""skill_index.py -- guard the skill descriptions and generate the per-plugin skill tables.

    py academy/scripts/skill_index.py --check            budget and form of every description
    py academy/scripts/skill_index.py --write            regenerate the Skills block in each plugin README
    py academy/scripts/skill_index.py --write --check-only   exit 1 if a README is stale (writes nothing)
    py academy/scripts/skill_index.py --verify-readmes       same as --write --check-only

Every skills/<name>/SKILL.md has a one-line ``description:`` in its frontmatter, a
single-quoted YAML scalar (a doubled '' is an apostrophe). Claude Code lists them all
in a limited budget, so --check fails when one is malformed, longer than MAX_DESC, or
the total exceeds MAX_TOTAL. The README tables are generated from the same lines, so
the descriptions stay the only place a skill is summarised. Stdlib only.
"""

import argparse
import glob
import os
import re
import sys

REPO = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
PLUGINS = ("academy", "author", "expert", "researcher", "scientist")
MAX_DESC = 280
MAX_TOTAL = 13000
BEGIN = ("<!-- skills:begin (generated by academy/scripts/skill_index.py; "
         "edit the skill's description instead) -->")
END = "<!-- skills:end -->"

_DESC = re.compile(r"^description: '((?:[^']|'')*)'$")
_NAME = re.compile(r"^name: *(\S+) *$")


def _rel(root, path):
    return os.path.relpath(path, root).replace(os.sep, "/")


def discover(root):
    """[(plugin_dir, path)] of every SKILL.md; plugin_dir is e.g. 'author' or 'domains/ts'."""
    out = []
    for pat in ("*/skills/*/SKILL.md", "domains/*/skills/*/SKILL.md"):
        for path in sorted(glob.glob(os.path.join(root, *pat.split("/")))):
            plugin = _rel(root, path).split("/skills/")[0]
            out.append((plugin, path))
    return out


def parse(path):
    """(name, description, problem); the frontmatter's name and description lines only."""
    name = desc = None
    problem = None
    try:
        with open(path, encoding="utf-8", newline="") as fh:
            lines = fh.read().splitlines()
    except OSError as exc:
        return None, None, "cannot read (%s)" % exc
    if not lines or lines[0] != "---":
        return None, None, "no frontmatter"
    for line in lines[1:]:
        if line == "---":
            break
        m = _NAME.match(line)
        if m and name is None:
            name = m.group(1)
        if line.startswith("description:"):
            m = _DESC.match(line)
            if m:
                desc = m.group(1).replace("''", "'")
            else:
                problem = "description is not a single-line single-quoted scalar"
    if name is None:
        problem = problem or "no name line"
    if desc is None and problem is None:
        problem = "no description line"
    return name, desc, problem


def collect(root):
    """[(plugin, name, description)] plus the list of problem lines."""
    skills, problems = [], []
    for plugin, path in discover(root):
        name, desc, problem = parse(path)
        where = _rel(root, path)
        if problem:
            problems.append("%s: %s" % (where, problem))
            continue
        skills.append((plugin, name, desc))
        if len(desc) > MAX_DESC:
            problems.append("%s: description is %d chars (max %d)" % (where, len(desc), MAX_DESC))
    return skills, problems


def check(root):
    skills, problems = collect(root)
    total = sum(len(d) for _, _, d in skills)
    if total > MAX_TOTAL:
        problems.append("total description length %d exceeds %d" % (total, MAX_TOTAL))
    longest = max((len(d) for _, _, d in skills), default=0)
    return problems, "%d skills, total %d chars, max %d" % (len(skills), total, longest)


def block(plugin, rows):
    lines = [BEGIN, "", "| Skill | What it does |", "|---|---|"]
    for name, desc in sorted(rows):
        lines.append("| /%s:%s | %s |" % (plugin, name, desc.replace("|", r"\|")))
    lines += ["", END]
    return "\n".join(lines)


def render(existing, plugin, rows):
    """The README text with the generated block in place (existing None: no README yet)."""
    blk = block(plugin, rows)
    if existing is None:
        return "# %s: the %s plugin\n\n## Skills\n\n%s\n" % (plugin, plugin, blk)
    b, e = existing.find(BEGIN), existing.find(END)
    if b != -1 and e > b:
        return existing[:b] + blk + existing[e + len(END):]
    text = existing if existing.endswith("\n") or not existing else existing + "\n"
    sep = "\n" if text else ""
    return text + sep + "## Skills\n\n" + blk + "\n"


def sync_readmes(root, write):
    """Names of the plugins whose README is stale; rewrites them when write is true."""
    skills, _ = collect(root)
    stale = []
    for plugin in PLUGINS:
        rows = [(n, d) for p, n, d in skills if p == plugin]
        if not rows:
            continue
        path = os.path.join(root, plugin, "README.md")
        existing = None
        if os.path.exists(path):
            with open(path, encoding="utf-8", newline="") as fh:
                existing = fh.read()
        new = render(existing, plugin, rows)
        if new != existing:
            stale.append(plugin)
            if write:
                os.makedirs(os.path.dirname(path), exist_ok=True)
                with open(path, "w", encoding="utf-8", newline="\n") as fh:
                    fh.write(new)
    return stale


def main(argv=None):
    ap = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    ap.add_argument("--root", default=REPO)
    ap.add_argument("--check", action="store_true")
    ap.add_argument("--write", action="store_true")
    ap.add_argument("--check-only", action="store_true")
    ap.add_argument("--verify-readmes", action="store_true")
    a = ap.parse_args(argv)
    verify = a.verify_readmes or (a.write and a.check_only)
    if not (a.check or a.write or verify):
        ap.error("give --check, --write or --verify-readmes")
    code = 0
    if a.check:
        problems, summary = check(a.root)
        for p in problems:
            print(p)
        if problems:
            code = 1
        else:
            print(summary)
    if verify:
        stale = sync_readmes(a.root, write=False)
        for p in stale:
            print("%s/README.md: skills block is stale (run skill_index.py --write)" % p)
        code = 1 if stale else code
        if not stale:
            print("READMEs up to date")
    elif a.write:
        for p in sync_readmes(a.root, write=True):
            print("wrote %s/README.md" % p)
    return code


if __name__ == "__main__":
    sys.exit(main())
