"""hot.py (the clerk's digest) and ledger_split.py (BI ledgers -> cards)."""

import json
import os
import unittest

import fixtures
import _academy as ac
import cards
import hot
import ledger_split as ls

LOG = ("2026-09-28T10:00:00\tlibrary_lookup\tclerk\tABC21\n"
       "2026-09-28T10:01:00\tlibrary_lookup\thuman\tXY20\n"
       "2026-09-28T10:02:00\tlibrary_verify_quote\tlibrarian\tABC21\n"
       "2026-09-28T10:03:00\tlibrary_search\tclerk\tperiodic points finite\n"
       "2026-09-28T10:04:00\tlibrary_missing\thuman\t-\n"
       "2026-09-28T10:05:00\tclaims_show\tclerk\tpaper:lem:x\n"
       "garbage line\n")


class HotTests(unittest.TestCase):
    def setUp(self):
        self.sb = fixtures.Sandbox()
        self.log = self.sb.write("papers/.academy/access.log", LOG)
        self.sb.write("papers/cards/ABC21/lemma-2-1.md", fixtures.card_text())

    def tearDown(self):
        self.sb.close()

    def test_tally(self):
        keys, queries, claims = hot.tally(hot.read_log([self.log]))
        self.assertEqual(keys["ABC21"][0], 2)
        self.assertEqual(keys["XY20"][0], 1)
        self.assertEqual(list(queries), ["periodic points finite"])
        self.assertEqual(list(claims), ["paper:lem:x"])

    def test_build_orders_and_marks(self):
        text = hot.build(self.sb.lib, [self.log], 50)
        self.assertTrue(text.startswith("<!-- generated by academy: expert/scripts/hot.py"))
        self.assertLess(text.index("### ABC21"), text.index("### XY20"))
        self.assertIn("**Lemma 2.1**", text)
        self.assertIn("The orbit of a periodic point is finite.", text)
        self.assertIn('Able-Baker-Charlie, "A paper"', text)
        self.assertIn("`paper:lem:x`", text)

    def test_size_limits(self):
        text = hot.build(self.sb.lib, [self.log], 1)
        self.assertIn("### ABC21", text)
        self.assertNotIn("### XY20", text)

    def test_tie_broken_by_latest(self):
        log = self.sb.write("papers/l2.log", "2026-09-01T00:00:00\tlibrary_lookup\tx\tAAA\n"
                                             "2026-09-02T00:00:00\tlibrary_lookup\tx\tZZZ\n")
        keys, _, _ = hot.tally(hot.read_log([log]))
        self.assertEqual([k for k, _ in hot.top(keys, 5)], ["ZZZ", "AAA"])

    def test_cli_writes_hot_md(self):
        code, out, err = fixtures.run_script("hot.py", None, ["--home", self.sb.lib])
        self.assertEqual(code, 0, err)
        self.assertIn("### ABC21", self.sb.read("papers/hot.md"))


SOURCES = """# Verified sources ledger

Preamble text.

## ABC21 — Able, Baker, Charlie, arXiv:2101.00001v2

Intro paragraph for ABC21.

- **Lemma 2.1** — source label `L:one`. Verbatim: "Let $M$ be a translation surface
  and let $x$ be a periodic point." Verdict: **match**, used in `lem:x` and
  `defn:y`. How read: **source** (v2, confirmed). 2026-09-19.
- **Theorem 3.4** — Verbatim: "Every nice surface is illuminated." Verdict:
  **mismatch**. How read: extraction. 2026-09-20.
- Bib data from Crossref. 2026-09-15.

**Later re-check, 2026-09-24.** Read `XY20.txt` again: "Any two points are finitely
blocked on a Veech surface." quoted from the extraction.

## XY20, ABC21 — two sources in one heading

- **ABC21, Lemma 2.1 again** — Verbatim: "Then the orbit of $x$ is finite." How
  read: **source**. 2026-09-21.

## Somebody, arXiv:1710.05505 (not in references.bib)

- **Theorem 1**: a statement. How read: abstract. 2026-09-18.
"""

RELATED = """# Related-work ledger

Keywords: illumination.

## 2026-09-19 — `lem:x` (`sections/a.tex`)

### Queries run

- "illumination"

## 2026-09-20 — second block

Nothing found.
"""


class SplitTests(unittest.TestCase):
    def setUp(self):
        self.sb = fixtures.Sandbox()
        self.out = os.path.join(self.sb.root, "out")

    def tearDown(self):
        self.sb.close()

    def test_convert(self):
        written, stats = ls.convert_sources(SOURCES, self.out, self.sb.lib,
                                            {"ABC21", "XY20"})
        rel = sorted(os.path.relpath(p, self.out).replace("\\", "/") for p in written)
        self.assertIn("cards/ABC21/lemma-2-1.md", rel)
        self.assertIn("cards/ABC21/theorem-3-4.md", rel)
        self.assertIn("cards/ABC21/entry.md", rel)
        self.assertIn("cards/ABC21/lemma-2-1-again.md", rel)     # the ABC21 prefix taken
        self.assertIn("cards/XY20/later-re-check-2026-09-24.md", rel)  # moved by evidence
        self.assertTrue(any(r.startswith("cards/_unkeyed/") for r in rel))
        self.assertTrue(os.path.isfile(os.path.join(self.out, "cards", "ABC21", "_intro.md")))
        self.assertEqual(stats["cards"], 6)
        self.assertEqual(stats["unkeyed_blocks"],
                         ["Somebody, arXiv:1710.05505 (not in references.bib)"])

        meta, body = cards.read_card(os.path.join(self.out, "cards", "ABC21",
                                                  "lemma-2-1.md"))
        self.assertEqual(meta["read_from"], "source")
        self.assertEqual(meta["verdict"], "match")
        self.assertEqual(meta["used_by"], ["paper:defn:y", "paper:lem:x"])
        self.assertEqual(meta["source_label"], "L:one")
        self.assertEqual(meta["checked"], "2026-09-19")
        self.assertEqual(meta["version"], "arXiv v2 (1 Jan 2021)")   # from the index row
        self.assertTrue(meta["migrated"])
        errs, warns, q = cards.validate_card(meta, body, self.sb.lib)
        self.assertEqual(errs, [])
        self.assertEqual(q["status"], "verified")
        self.assertIn("## Ledger text", body)

        meta, _ = cards.read_card(os.path.join(self.out, "cards", "ABC21",
                                               "theorem-3-4.md"))
        self.assertEqual((meta["read_from"], meta["verdict"]), ("extraction", "mismatch"))

    def test_related(self):
        written = ls.convert_related(RELATED, self.out)
        names = sorted(os.path.basename(p) for p in written)
        self.assertEqual(names, ["2026-09-19-lem-x-sections-a-tex.md",
                                 "2026-09-20-second-block.md", "_header.md"])
        with open(written[1], encoding="utf-8") as fh:
            self.assertIn("### Queries run", fh.read())

    def test_refuses_to_write_into_a_home(self):
        src = self.sb.write("s.md", SOURCES)
        code, out, err = fixtures.run_script(
            "ledger_split.py", None, ["--sources", src, "--out",
                                      os.path.join(self.sb.lib, "x")])
        self.assertEqual(code, 2)
        self.assertIn("home of expert@main", err)
        code, out, err = fixtures.run_script(
            "ledger_split.py", None, ["--sources", src, "--out", self.out, "--library",
                                      self.sb.lib])
        self.assertEqual(code, 0, err)
        with open(os.path.join(self.out, "stats.json"), encoding="utf-8") as fh:
            st = json.load(fh)
        self.assertEqual(st["cards"], 6)
        self.assertEqual(len(st["cards_in_order"]), 6)


VERDICTS = """# Verdicts ledger

Preamble.

## lem:x -- 2026-09-23 (primary-model pair)

- run A: proved modulo named inputs / CONFIRMED / claude-fable-5-1 (primary) -- blocking:
  none in the proof itself.
- run B: partial / PLAUSIBLE / claude-opus-5[1m] (fallback; primary is
  fable) -- blocking: step 3.
- outcome: **stays blue.** Both agree.
- run A adds a finding that is not a run record.

Narrative paragraph.

### primary-model pair, same day

- run A: partial / CONFIRMED / claude-fable-5-1 (primary) -- blocking: S10.
- run B: partial / CONFIRMED / claude-fable-5-1 (primary) -- blocking: S10 again.
- outcome: **stays blue.**

## lem:y -- 2026-09-20

Something that is not a run bullet at all.
"""


class SplitRecordsTests(unittest.TestCase):
    """Card status, review records, and the manifest round trip (Group F)."""

    def setUp(self):
        self.sb = fixtures.Sandbox()
        self.out = os.path.join(self.sb.root, "out")

    def tearDown(self):
        self.sb.close()

    def test_card_status_never_repairs_the_quote(self):
        _w, stats = ls.convert_sources(SOURCES, self.out, self.sb.lib, {"ABC21", "XY20"})
        meta, body = cards.read_card(os.path.join(self.out, "cards", "ABC21", "lemma-2-1.md"))
        self.assertEqual(meta["status"], "verified")
        meta, body = cards.read_card(os.path.join(self.out, "cards", "ABC21",
                                                  "theorem-3-4.md"))
        self.assertEqual(meta["status"], "unverified")
        self.assertIn("not found", meta["status_reason"])
        self.assertIn("Every nice surface is illuminated.", body)   # quote kept as given
        meta, _ = cards.read_card(os.path.join(self.out, "cards", "ABC21", "entry.md"))
        self.assertEqual(meta["status"], "unverified")
        self.assertIn("no verbatim quote", meta["status_reason"])
        self.assertEqual(sum(stats["status"].values()), stats["cards"])

    def test_verified_status_with_failing_quote_is_an_error(self):
        meta = {"key": "ABC21", "pinpoint": "Thm 9", "version": "v2", "read_from": "extraction",
                "status": "verified"}
        text = cards.render_card(meta, "S.", ["H."], "A sentence that the source never says.")
        m, b = ac.read_frontmatter(text)
        errs, _w, _q = cards.validate_card(m, b, self.sb.lib)
        self.assertTrue(any("status verified" in e for e in errs))

    def test_extract_quote_needs_an_anchor_nearby(self):
        b = ('- **X** which the proposition reads off the tiling ("a long parenthetical '
             'remark here"), so this is fine.')
        self.assertEqual(ls.extract_quote(b), "")

    def test_extract_quote_skips_a_heading_named_before_the_colon(self):
        # AW21/1-point-marking: the ledger names the paragraph in quotes before the
        # colon that actually introduces the relied-on statement.
        b = ('- **X** verbatim from the source, unnumbered paragraph "Marked points on '
             'translation surfaces" in the Introduction: "Define an n-point marking '
             'over M to be an affine invariant submanifold."')
        self.assertEqual(ls.extract_quote(b),
                          "Define an n-point marking over M to be an affine invariant "
                          "submanifold.")

    def test_extract_quote_skips_two_headings_named_before_the_colon(self):
        # AW21/scope-of-aw21-s-base-stratum-no-marked-points: two headings quoted back
        # to back before the real colon-introduced quote.
        b = ('- **X** Verbatim from `AW21.src/main.tex:277,279` (S1, "Affine invariant '
             'submanifolds" / "Marked points on translation surfaces" paragraphs, '
             'immediately before `L:FiberDim`): "Given a partition of the stratum into '
             'pieces of positive integers."')
        self.assertEqual(ls.extract_quote(b),
                          "Given a partition of the stratum into pieces of positive "
                          "integers.")

    def test_extract_quote_finds_a_pinpoint_quote_with_no_anchor_word(self):
        # MS91/lemma-4-2: a bare "(`key.txt:lines`): \"quote\"" with no "verbatim",
        # "quoted" or "reads" anywhere in the bullet.
        b = ('- **LEMMA 4.2** (`MS91.txt:1033-1034`): "The map is injective and for '
             'distinct points the sets are disjoint."')
        self.assertEqual(ls.extract_quote(b),
                          "The map is injective and for distinct points the sets are "
                          "disjoint.")

    def test_extract_quote_pinpoint_fallback_does_not_fire_on_a_cref(self):
        # Vo96a/verdict-against-prop-vorobets-lift: a \cref/\cite citation (no
        # backtick file:line pinpoint) must not be mistaken for one, even though the
        # bullet's prose happens to say "reads off" nowhere near a real quotation.
        b = ('- **Verdict** notes that the paper already says: which \\cite[Prop. '
             '5.1]{Vo96a} reads off the tiling and which \\cref{prop:vorobets-lift} '
             'presupposes, so this is not a new mismatch worth a quote here at all.')
        self.assertEqual(ls.extract_quote(b), "")

    def test_verdicts_records_and_unparsed(self):
        pieces = []
        _w, st = ls.convert_verdicts(VERDICTS, self.out, pieces=pieces)
        self.assertEqual(st["records"], 2)
        self.assertEqual(len(st["unparsed"]), 1)
        a = os.path.join(self.out, "reviews", "paper", "lem-x", "2026-09-23-primary-model-pair",
                         "A.md")
        with open(a, encoding="utf-8") as fh:
            meta, body = ac.read_frontmatter(fh.read())
        self.assertEqual((meta["verdict"], meta["model"], meta["model_note"]),
                         ("CONFIRMED", "claude-fable-5-1", "primary"))
        self.assertIsNone(meta["run_id"])                   # never invented
        b = a.replace("A.md", "B.md")
        with open(b, encoding="utf-8") as fh:
            meta, _ = ac.read_frontmatter(fh.read())
        self.assertEqual(meta["model_note"], "fallback; primary is fable")
        dec = a.replace("A.md", "decision.md")
        with open(dec, encoding="utf-8") as fh:
            text = fh.read()
        self.assertIn("run A adds a finding", text)
        self.assertIn("outcome: stays blue", text)
        self.assertTrue(os.path.isfile(os.path.join(
            self.out, "reviews", "paper", "lem-x",
            "2026-09-23-primary-model-pair-same-day", "B.md")))
        self.assertTrue(os.path.isfile(os.path.join(self.out, "reviews", "_unparsed.md")))

    def test_manifest_round_trip(self):
        for name, text, conv in (
                ("sources", SOURCES, lambda t, p: ls.convert_sources(
                    t, self.out, self.sb.lib, {"ABC21", "XY20"}, pieces=p)),
                ("related_work", RELATED, lambda t, p: ls.convert_related(t, self.out,
                                                                          pieces=p)),
                ("verdicts", VERDICTS, lambda t, p: ls.convert_verdicts(t, self.out,
                                                                        pieces=p))):
            pieces = []
            conv(text, pieces)
            man, problems = ls.build_manifest(text, pieces, name, "author@main")
            self.assertEqual(problems, [], name)
            self.assertEqual(ls.render_manifest(self.out, man), text, name)

    def test_cli_and_views(self):
        src = self.sb.write("d/sources.md", SOURCES)
        self.sb.write("d/related_work.md", RELATED)
        self.sb.write("d/verdicts.md", VERDICTS)
        d = os.path.dirname(src)
        code, out, err = fixtures.run_script(
            "ledger_split.py", None,
            ["--sources", src, "--related", os.path.join(d, "related_work.md"),
             "--verdicts", os.path.join(d, "verdicts.md"), "--out", self.out,
             "--library", self.sb.lib])
        self.assertEqual(code, 0, err)
        with open(os.path.join(self.out, "ledger-split-report.md"), encoding="utf-8") as fh:
            rep = fh.read()
        self.assertIn("## Unmapped", rep)
        self.assertIn("_unparsed.md", rep)
        code, out, err = fixtures.run_script("ledger_views.py", None,
                                             ["--home", self.out, "--check", d])
        self.assertEqual(code, 0, out + err)
        code, out, err = fixtures.run_script("ledger_views.py", None, ["--home", self.out])
        self.assertEqual(code, 0, err)
        with open(os.path.join(self.out, "views", "author@main", "verdicts.md"),
                  encoding="utf-8") as fh:
            self.assertIn("generated by academy", fh.readline())


if __name__ == "__main__":
    unittest.main()
