"""Tests for scripts/skill_index.py: the skill-description guard and the generated
per-plugin skill tables. Fabricated plugin trees in temp directories; one test runs
--check against the real repo.

Run from the repo root:  py -m unittest discover academy/tests
"""

import io
import os
import shutil
import sys
import tempfile
import unittest
from contextlib import redirect_stdout

HERE = os.path.dirname(os.path.abspath(__file__))
PLUGIN = os.path.dirname(HERE)
REPO = os.path.dirname(PLUGIN)
sys.path.insert(0, os.path.join(PLUGIN, "scripts"))

import skill_index  # noqa: E402

BEGIN = ("<!-- skills:begin (generated by academy/scripts/skill_index.py; "
         "edit the skill's description instead) -->")
END = "<!-- skills:end -->"


def run(*argv):
    buf = io.StringIO()
    with redirect_stdout(buf):
        code = skill_index.main(list(argv))
    return code, buf.getvalue()


class Tree(unittest.TestCase):
    def setUp(self):
        self.root = tempfile.mkdtemp()
        self.addCleanup(shutil.rmtree, self.root, True)

    def skill(self, rel, name, desc_line):
        d = os.path.join(self.root, rel, "skills", name)
        os.makedirs(d, exist_ok=True)
        with open(os.path.join(d, "SKILL.md"), "w", newline="\n") as fh:
            fh.write("---\nname: %s\n%s\n---\n\nBody.\n" % (name, desc_line))

    def q(self, text):
        return "description: '%s'" % text.replace("'", "''")

    def readme(self, plugin, text=None):
        p = os.path.join(self.root, plugin, "README.md")
        if text is not None:
            os.makedirs(os.path.dirname(p), exist_ok=True)
            with open(p, "w", newline="\n") as fh:
                fh.write(text)
        return p

    def read(self, p):
        with open(p, newline="") as fh:
            return fh.read()


class TestCheck(Tree):
    def test_valid_tree_passes(self):
        self.skill("author", "one", self.q("Does it."))
        self.skill("domains/d", "two", self.q("Isn't long."))
        code, out = run("--root", self.root, "--check")
        self.assertEqual(code, 0, out)
        self.assertIn("2 skills, total 19 chars, max 11", out)

    def test_overlong_description_fails(self):
        self.skill("author", "one", self.q("x" * 281))
        code, out = run("--root", self.root, "--check")
        self.assertEqual(code, 1)
        self.assertIn("one", out)
        self.assertIn("281", out)

    def test_unquoted_description_fails(self):
        self.skill("author", "one", "description: Plain text")
        code, out = run("--root", self.root, "--check")
        self.assertEqual(code, 1)
        self.assertIn("one", out)

    def test_total_over_budget_fails(self):
        for i in range(60):
            self.skill("author", "s%02d" % i, self.q("y" * 250))
        code, out = run("--root", self.root, "--check")
        self.assertEqual(code, 1)
        self.assertIn("13000", out)

    def test_apostrophe_unquoted_counts_once(self):
        self.skill("author", "one", self.q("a'b"))
        code, out = run("--root", self.root, "--check")
        self.assertEqual(code, 0, out)
        self.assertIn("max 3", out)


class TestWrite(Tree):
    def setUp(self):
        super().setUp()
        self.skill("author", "zeta", self.q("Last one."))
        self.skill("author", "beta", self.q("It's first."))
        self.skill("domains/d", "dom", self.q("Domain skill."))

    def test_inserts_sorted_table_under_new_heading(self):
        p = self.readme("author", "# author\n\nHand-written prose.\n")
        code, out = run("--root", self.root, "--write")
        self.assertEqual(code, 0, out)
        text = self.read(p)
        self.assertTrue(text.startswith("# author\n\nHand-written prose.\n"))
        self.assertIn("## Skills", text)
        self.assertIn(BEGIN, text)
        self.assertIn(END, text)
        self.assertIn("| Skill | What it does |", text)
        self.assertLess(text.index("/author:beta"), text.index("/author:zeta"))
        self.assertIn("| /author:beta | It's first. |", text)
        self.assertNotIn("dom", text.split("## Skills")[1].replace("Domain", ""))

    def test_idempotent(self):
        p = self.readme("author", "# author\n")
        run("--root", self.root, "--write")
        first = self.read(p)
        run("--root", self.root, "--write")
        self.assertEqual(first, self.read(p))
        self.assertEqual(first.count(BEGIN), 1)

    def test_creates_missing_readme(self):
        code, _ = run("--root", self.root, "--write")
        self.assertEqual(code, 0)
        text = self.read(self.readme("author"))
        self.assertTrue(text.startswith("# author: "))
        self.assertIn("/author:zeta", text)

    def test_no_readme_for_domain_pack(self):
        run("--root", self.root, "--write")
        self.assertFalse(os.path.exists(os.path.join(self.root, "domains", "d", "README.md")))

    def test_preserves_text_around_existing_block(self):
        p = self.readme("author", "# author\n\nBefore.\n\n" + BEGIN + "\nold\n" + END + "\n\nAfter.\n")
        run("--root", self.root, "--write")
        text = self.read(p)
        self.assertIn("Before.\n", text)
        self.assertTrue(text.rstrip().endswith("After."))
        self.assertNotIn("\nold\n", text)
        self.assertIn("/author:beta", text)

    def test_lf_endings(self):
        p = self.readme("author", "# author\n")
        run("--root", self.root, "--write")
        with open(p, "rb") as fh:
            self.assertNotIn(b"\r", fh.read())


class TestVerify(Tree):
    def test_stale_readme_detected_then_fresh(self):
        self.skill("author", "one", self.q("Original."))
        self.readme("author", "# author\n")
        run("--root", self.root, "--write")
        code, _ = run("--root", self.root, "--write", "--check-only")
        self.assertEqual(code, 0)
        self.skill("author", "one", self.q("Changed."))
        code, out = run("--root", self.root, "--write", "--check-only")
        self.assertEqual(code, 1)
        self.assertIn("author", out)

    def test_check_only_does_not_write(self):
        self.skill("author", "one", self.q("Original."))
        p = self.readme("author", "# author\n")
        code, _ = run("--root", self.root, "--write", "--check-only")
        self.assertEqual(code, 1)
        self.assertEqual(self.read(p), "# author\n")


class TestRealRepo(unittest.TestCase):
    def test_real_repo_passes_check(self):
        code, out = run("--root", REPO, "--check")
        self.assertEqual(code, 0, out)


if __name__ == "__main__":
    unittest.main()
