"""Tests for the base plugin's hooks, fed JSON fixture events on stdin.

Each hook script is run as a subprocess exactly as Claude Code runs it, against a
throw-away workspace (``ACADEMY_WORKSPACE``), homes and board in a temp directory.
Run from the repo root:  py -m unittest discover academy/tests
"""

import io
import json
import os
import shutil
import subprocess
import sys
import tempfile
import unittest

HERE = os.path.dirname(os.path.abspath(__file__))
PLUGIN = os.path.dirname(HERE)
REPO = os.path.dirname(PLUGIN)
SCRIPTS = os.path.join(PLUGIN, "scripts")
sys.path.insert(0, os.path.join(PLUGIN, "lib"))

import academy_common as ac  # noqa: E402

HAVE_GIT = shutil.which("git") is not None
MARKER_HEADER = "<!-- generated by academy: test fixture; do not edit -->\n"


def run_hook(script, event, env=None, cwd=None):
    """Run one hook script with ``event`` on stdin; return (returncode, parsed stdout|None)."""
    full_env = dict(os.environ)
    full_env.update(env or {})
    res = subprocess.run([sys.executable, os.path.join(SCRIPTS, script)],
                         input=json.dumps(event).encode("utf-8"),
                         capture_output=True, env=full_env, cwd=cwd, timeout=60)
    out = res.stdout.decode("utf-8").strip()
    return res.returncode, (json.loads(out) if out else None), res.stderr.decode(
        "utf-8", "replace")


def decision(out):
    return (out or {}).get("hookSpecificOutput", {}).get("permissionDecision")


def config_for(role, instance, ns=None, views=None):
    cfg = {"schema": 1, "role": role, "instance": instance,
           "domains": ["test-domain"],
           "paths": {k: k for k in ac.REQUIRED_PATHS[role]},
           "registry": {"profile": "none"}, role: {}}
    cfg["paths"]["views"] = views or ["views", "Drafts/statements.md"]
    if ns:
        cfg["ns"] = ns
        cfg["registry"] = {"profile": "paper", "root": "claims"}
    return cfg


def ticket_text(tid, frm, to, status="open", thread=None, **extra):
    meta = {"id": tid, "title": "Fixture " + tid, "kind": "verify", "from": frm,
            "to": to, "status": status, "priority": "normal", "ask": "Check it.",
            "deliverable": "A packet.", "refs": [], "blocks": [], "waiting_on": [],
            "budget": {"runs": 1, "max_model": "sonnet"}, "packets": [],
            "created": "2026-09-27", "updated": "2026-09-27"}
    meta.update(extra)
    text = ac.new_ticket(meta)
    for who, line in thread or [("human", "opened")]:
        meta2, body = ac.read_frontmatter(text)
        text = ac.write_frontmatter(meta2, ac.append_thread(body, who, line,
                                                            date="2026-09-27"))
    return text


def packet_text(pid, instance, state="open"):
    meta = {"packet": pid, "title": "Fixture " + pid, "instance": instance,
            "kind": "other", "by": instance, "state": state, "created": "2026-09-27"}
    body = ("\n## Summary\n\nA fixture.\n\n## Produced\n\nNothing.\n\n"
            "## Established vs assumed\n\nNothing.\n\n## Evidence\n\nNone.\n\n"
            "## Decisions needed\n\nNone.\n\n## Machine notes\n\nNone.\n\n## Decision\n\n")
    if state == "decided":
        body += "- D0: ack | 2026-09-27 | human\n"
    return ac.write_frontmatter(meta, body)


class Fixture(unittest.TestCase):
    """A workspace with two instances (author@t, expert@t), their homes and a board."""

    def setUp(self):
        self.tmp = tempfile.mkdtemp(prefix="academy-hooks-")
        self.board = os.path.join(self.tmp, "board")
        self.author_home = os.path.join(self.tmp, "homes", "author")
        self.expert_home = os.path.join(self.tmp, "homes", "expert")
        self.outside = os.path.join(self.tmp, "elsewhere")
        for d in (self.board, self.author_home, self.expert_home, self.outside):
            os.makedirs(d)
        ws = {"instances": {
            "author@t": {"role": "author", "home": self.author_home.replace("\\", "/"),
                         "domains": ["test-domain"], "ns": "paper"},
            "expert@t": {"role": "expert", "home": self.expert_home.replace("\\", "/"),
                         "domains": ["test-domain"]}},
            "board": self.board.replace("\\", "/"), "human": {"name": "Roey"}}
        self.ws_path = self.write(os.path.join(self.tmp, "workspace.json"), json.dumps(ws))
        self.write(os.path.join(self.author_home, ".claude", "academy.json"),
                   json.dumps(config_for("author", "author@t", ns="paper")))
        self.write(os.path.join(self.expert_home, ".claude", "academy.json"),
                   json.dumps(config_for("expert", "expert@t")))
        self.callers = os.path.join(self.tmp, "callers")
        self.env = {"ACADEMY_WORKSPACE": self.ws_path, "ACADEMY_BOARD_COMMIT": "0",
                    "ACADEMY_CALLER_DIR": self.callers}

    def tearDown(self):
        shutil.rmtree(self.tmp, ignore_errors=True)

    @staticmethod
    def write(path, text):
        os.makedirs(os.path.dirname(path), exist_ok=True)
        with open(path, "w", encoding="utf-8", newline="\n") as fh:
            fh.write(text)
        return path

    def git(self, *args):
        res = subprocess.run(["git", "-C", self.board] + list(args), capture_output=True)
        self.assertEqual(res.returncode, 0, res.stderr.decode("utf-8", "replace"))
        return res.stdout.decode("utf-8", "replace")

    def init_board_repo(self):
        self.git("init", "-q")
        self.git("config", "user.email", "test@example.invalid")
        self.git("config", "user.name", "Test")
        self.git("config", "commit.gpgsign", "false")

    def commit_all(self):
        self.git("add", "-A")
        self.git("commit", "-q", "-m", "fixture")


# ---------------------------------------------------------------------------
# mcp_write_gate
# ---------------------------------------------------------------------------

class McpWriteGateTests(Fixture):
    def gate(self, tool, agent=None, server="mcp__academy__", **extra):
        event = {"hook_event_name": "PreToolUse", "tool_name": server + tool,
                 "tool_input": {}, "cwd": self.author_home}
        if agent:
            event["agent_type"] = agent
        event.update(extra)
        rc, out, err = run_hook("mcp_write_gate.py", event, self.env)
        self.assertEqual(rc, 0, err)
        return decision(out), out

    def test_human_may_call_everything(self):
        for tool in ("claims_set_status", "packets_decide", "queue_add", "claims_show"):
            self.assertIsNone(self.gate(tool)[0], tool)

    def test_set_status_by_rigor_reviewer_denied(self):
        dec, out = self.gate("claims_set_status", "expert:rigor-reviewer")
        self.assertEqual(dec, "deny")
        self.assertIn("rigor-reviewer", out["hookSpecificOutput"]["permissionDecisionReason"])

    def test_set_status_by_claim_keeper_allowed(self):
        self.assertIsNone(self.gate("claims_set_status", "researcher:claim-keeper")[0])

    def test_namespaced_and_bare_names_agree(self):
        for agent in ("author:math-writer", "math-writer", "Author:Math-Writer",
                      "paper:math-writer"):
            self.assertIsNone(self.gate("tickets_create", agent)[0], agent)
            self.assertEqual(self.gate("claims_set_status", agent)[0], "deny", agent)

    def test_plugin_server_prefix(self):
        server = "mcp__plugin_academy_academy__"
        self.assertEqual(self.gate("tickets_create", "expert:clerk", server)[0], "deny")
        self.assertIsNone(self.gate("tickets_create", "author:math-writer", server)[0])

    def test_readonly_agents_may_read(self):
        for agent in ("expert:rigor-reviewer", "expert:clerk", "academy:explainer"):
            self.assertIsNone(self.gate("claims_show", agent)[0], agent)
            self.assertIsNone(self.gate("library_lookup", agent)[0], agent)
            self.assertEqual(self.gate("tickets_update", agent)[0], "deny", agent)

    def test_packets_decide_is_human_only(self):
        self.assertEqual(self.gate("packets_decide", "academy:concierge")[0], "deny")

    def test_queue_add(self):
        self.assertIsNone(self.gate("queue_add", "scientist:experimenter")[0])
        self.assertEqual(self.gate("queue_add", "author:math-writer")[0], "deny")

    def test_agent_outside_roster(self):
        self.assertEqual(self.gate("claims_new", "general-purpose")[0], "deny")
        self.assertIsNone(self.gate("claims_show", "general-purpose")[0])

    def test_launched_agent_is_not_the_caller(self):
        dec, _ = self.gate("claims_set_status", "expert:rigor-reviewer",
                           tool_input={"subagent_type": "researcher:claim-keeper"})
        self.assertEqual(dec, "deny")

    def test_other_servers_and_tools_ignored(self):
        self.assertIsNone(self.gate("claims_set_status", "expert:rigor-reviewer",
                                    "mcp__other__")[0])
        self.assertIsNone(self.gate("", "expert:rigor-reviewer", "Bash")[0])

    def test_caller_argument_denied_for_everyone(self):
        for agent in (None, "researcher:claim-keeper"):
            dec, out = self.gate("claims_show", agent,
                                 tool_input={"id": "lab:x", "caller": "human"})
            self.assertEqual(dec, "deny", agent)
            self.assertIn("reserved", out["hookSpecificOutput"]["permissionDecisionReason"])

    def test_allowed_call_records_the_caller(self):
        args = {"id": "lab:x", "status": "proved"}
        self.gate("claims_set_status", "researcher:claim-keeper", tool_input=args)
        self.assertEqual(ac.claim_caller("claims_set_status", args, folder=self.callers),
                         "researcher:claim-keeper")
        self.gate("claims_set_status", None, tool_input=args)
        self.assertEqual(ac.claim_caller("claims_set_status", args, folder=self.callers),
                         "human")
        self.assertIsNone(ac.claim_caller("claims_set_status", args, folder=self.callers))

    def test_denied_call_records_nothing(self):
        self.gate("claims_set_status", "expert:rigor-reviewer", tool_input={"id": "a"})
        self.assertFalse(os.path.isdir(self.callers) and os.listdir(self.callers))

    def test_malformed_event_is_silent(self):
        res = subprocess.run([sys.executable, os.path.join(SCRIPTS, "mcp_write_gate.py")],
                             input=b"not json", capture_output=True, timeout=60)
        self.assertEqual(res.returncode, 0)
        self.assertEqual(res.stdout.strip(), b"")

    def test_non_ascii_argument_record_matches_the_server_key(self):
        """T-0070: Claude Code writes the event as UTF-8 bytes. The hook must record it
        under the key the server computes (``call_key`` via ``claim_caller``) even when
        Python's stdin text layer uses the ANSI codepage (cp1255 on the lab laptop)."""
        tool = "tickets_update"
        args = {"id": "T-0001", "result_detail": "n = 3 ± 1 — café"}
        event = {"hook_event_name": "PreToolUse",
                 "tool_name": "mcp__plugin_academy_academy__" + tool,
                 "tool_input": args, "cwd": self.author_home}
        payload = json.dumps(event, ensure_ascii=False).encode("utf-8")
        self.assertIn(b"\xc2\xb1", payload)         # raw UTF-8, not a \u escape
        cases = {"stdin text layer in cp1255": ({"PYTHONIOENCODING": "cp1255"},
                                                ("PYTHONUTF8",)),
                 "no encoding variables (as launched)": ({}, ("PYTHONIOENCODING",
                                                              "PYTHONUTF8"))}
        for label, (extra, drop) in cases.items():
            with self.subTest(label):
                shutil.rmtree(self.callers, ignore_errors=True)
                env = dict(os.environ)
                env.update(self.env)
                env.update(extra)
                for name in drop:
                    env.pop(name, None)
                res = subprocess.run(
                    [sys.executable, os.path.join(SCRIPTS, "mcp_write_gate.py")],
                    input=payload, capture_output=True, env=env, timeout=60)
                self.assertEqual(res.returncode, 0, res.stderr.decode("utf-8", "replace"))
                names = os.listdir(self.callers) if os.path.isdir(self.callers) else []
                self.assertEqual([n.split("-", 1)[0] for n in names],
                                 [ac.call_key(tool, args)])
                self.assertEqual(ac.claim_caller(tool, args, folder=self.callers), "human")


class ReadEventEncodingTests(unittest.TestCase):
    """``read_event`` decodes the hook event as UTF-8 whatever the stdin text layer's
    encoding (T-0070), and still never raises."""

    RAW = json.dumps({"a": "± — é"}, ensure_ascii=False).encode("utf-8")

    @staticmethod
    def ansi_stdin(raw):
        """A text stream like Windows ``sys.stdin``: bytes underneath, cp1255 on top."""
        return io.TextIOWrapper(io.BytesIO(raw), encoding="cp1255")

    def test_text_stream_in_ansi_codepage_is_read_as_utf8(self):
        self.assertEqual(ac.read_event(self.ansi_stdin(self.RAW)),
                         {"a": "± — é"})

    def test_utf8_bom_is_tolerated(self):
        raw = b"\xef\xbb\xbf" + self.RAW
        self.assertEqual(ac.read_event(io.BytesIO(raw)), {"a": "± — é"})
        self.assertEqual(ac.read_event(self.ansi_stdin(raw)),
                         {"a": "± — é"})

    def test_invalid_utf8_is_replaced_not_raised(self):
        self.assertEqual(ac.read_event(self.ansi_stdin(b'{"a": "\xff"}')),
                         {"a": "�"})

    def test_unreadable_streams_give_empty_event(self):
        class Broken:
            def read(self):
                raise OSError("closed")

        class BrokenBuffer:
            buffer = Broken()

            def read(self):
                raise AssertionError("the text layer must not be read")

        self.assertEqual(ac.read_event(Broken()), {})
        self.assertEqual(ac.read_event(BrokenBuffer()), {})


# ---------------------------------------------------------------------------
# generated_view_guard
# ---------------------------------------------------------------------------

class GeneratedViewGuardTests(Fixture):
    def guard(self, path, agent=None, tool="Edit", cwd=None):
        event = {"hook_event_name": "PreToolUse", "tool_name": tool,
                 "tool_input": {"file_path": path, "old_string": "a", "new_string": "b"},
                 "cwd": cwd or self.outside}
        if agent:
            event["agent_type"] = agent
        rc, out, err = run_hook("generated_view_guard.py", event, self.env)
        self.assertEqual(rc, 0, err)
        return decision(out)

    def test_marker_denied_for_everyone(self):
        p = self.write(os.path.join(self.outside, "INDEX.md"),
                       MARKER_HEADER + "# Index\n")
        for agent in (None, "author:math-editor", "researcher:claim-keeper"):
            for tool in ("Edit", "Write", "MultiEdit"):
                self.assertEqual(self.guard(p, agent, tool), "deny", (agent, tool))

    def test_marker_forms(self):
        for i, header in enumerate(("% Generated by academy (check_paper); do not edit\n",
                                    "\n\n# generated by academy: views.py\n")):
            p = self.write(os.path.join(self.outside, "v%d.txt" % i), header + "x\n")
            self.assertEqual(self.guard(p), "deny", header)

    def test_marker_after_the_header_lines_passes(self):
        p = self.write(os.path.join(self.outside, "notes.md"),
                       "a\nb\nc\nd\ne\nf\n" + MARKER_HEADER)
        self.assertIsNone(self.guard(p))

    def test_caller_dir_guarded(self):
        p = os.path.join(self.callers, "abc-1.json")
        for tool in ("Edit", "Write"):
            self.assertEqual(self.guard(p, "author:math-writer", tool), "deny", tool)
        for tool, cmd in (("Bash", "echo x > %s/f.json" % self.callers.replace("\\", "/")),
                          ("PowerShell", r"Set-Content ~\.claude\academy\callers\f.json x")):
            event = {"hook_event_name": "PreToolUse", "tool_name": tool,
                     "tool_input": {"command": cmd}, "cwd": self.outside,
                     "agent_type": "author:math-writer"}
            rc, out, err = run_hook("generated_view_guard.py", event, self.env)
            self.assertEqual(decision(out), "deny", cmd)
        event = {"hook_event_name": "PreToolUse", "tool_name": "Bash",
                 "tool_input": {"command": "ls"}, "cwd": self.outside}
        self.assertIsNone(decision(run_hook("generated_view_guard.py", event, self.env)[1]))

    def test_plain_file_passes(self):
        p = self.write(os.path.join(self.author_home, "sections", "intro.tex"), "x\n")
        self.assertIsNone(self.guard(p, "author:math-writer"))
        self.assertIsNone(self.guard(os.path.join(self.outside, "new.md"), tool="Write"))

    def test_paths_views_denied_even_without_marker(self):
        p = self.write(os.path.join(self.author_home, "Drafts", "statements.md"), "old\n")
        self.assertEqual(self.guard(p, "author:math-editor"), "deny")
        new = os.path.join(self.author_home, "views", "graph.md")
        self.assertEqual(self.guard(new, tool="Write"), "deny")

    def test_relative_path_uses_cwd(self):
        self.write(os.path.join(self.author_home, "Drafts", "statements.md"), "old\n")
        self.assertEqual(self.guard("Drafts/statements.md", cwd=self.author_home), "deny")
        self.assertIsNone(self.guard("Drafts/agenda.md", cwd=self.author_home))


# ---------------------------------------------------------------------------
# explainer_write_guard
# ---------------------------------------------------------------------------

class ExplainerWriteGuardTests(Fixture):
    def guard(self, path, agent="academy:explainer", tool="Write"):
        event = {"hook_event_name": "PreToolUse", "tool_name": tool,
                 "tool_input": {"file_path": path, "content": "{}"}, "cwd": self.outside}
        if agent:
            event["agent_type"] = agent
        rc, out, err = run_hook("explainer_write_guard.py", event, self.env)
        self.assertEqual(rc, 0, err)
        return decision(out)

    def test_bundle_in_deep_dives_allowed(self):
        p = os.path.join(self.board, "deep-dives", "dd-claim-x.json")
        self.assertIsNone(self.guard(p))
        self.assertIsNone(self.guard(p, agent="explainer"))

    def test_everything_else_denied(self):
        for p, tool in ((os.path.join(self.author_home, "sections", "a.tex"), "Write"),
                        (os.path.join(self.board, "deep-dives", "x.html"), "Write"),
                        (os.path.join(self.board, "deep-dives", "sub", "x.json"), "Write"),
                        (os.path.join(self.board, "author@t", "T-0001-x.md"), "Write"),
                        (os.path.join(self.board, "deep-dives", "x.json"), "Edit"),
                        (os.path.join(self.callers, "f.json"), "Write")):
            self.assertEqual(self.guard(p, tool=tool), "deny", (p, tool))

    def test_other_agents_and_human_silent(self):
        p = os.path.join(self.author_home, "sections", "a.tex")
        for agent in (None, "author:math-writer", "other:explainer"):
            self.assertIsNone(self.guard(p, agent=agent), agent)


# ---------------------------------------------------------------------------
# ticket_edit_check
# ---------------------------------------------------------------------------

class TicketEditCheckTests(Fixture):
    def check(self, path, agent=None, cwd=None, tool="Edit"):
        event = {"hook_event_name": "PostToolUse", "tool_name": tool,
                 "tool_input": {"file_path": path}, "tool_response": {"success": True},
                 "cwd": cwd or self.author_home}
        if agent:
            event["agent_type"] = agent
        rc, out, err = run_hook("ticket_edit_check.py", event, self.env)
        self.assertEqual(rc, 0, err)
        if out is None:
            return None
        self.assertEqual(out.get("decision"), "block")
        return out["reason"]

    def tpath(self, folder, tid):
        return os.path.join(self.board, folder, "%s-fixture-%s.md" % (tid, tid.lower()))

    def test_files_off_the_board_are_ignored(self):
        p = self.write(os.path.join(self.author_home, "T-0001-x.md"), "garbage")
        self.assertIsNone(self.check(p, "author:math-writer"))
        p = self.write(os.path.join(self.board, "human", "RESUME.md"), "free text\n")
        self.assertIsNone(self.check(p))

    def test_valid_ticket_by_human_passes(self):
        p = self.write(self.tpath("expert@t", "T-0001"),
                       ticket_text("T-0001", "author@t", "expert@t"))
        self.assertIsNone(self.check(p))

    def test_schema_errors_reported(self):
        p = self.write(self.tpath("expert@t", "T-0002"),
                       ticket_text("T-0002", "author@t", "expert@t", status="done"))
        self.assertIn("status 'done'", self.check(p))
        p = self.write(self.tpath("expert@t", "T-0003"),
                       ticket_text("T-0003", "author@t", "expert@t", status="delivered"))
        self.assertIn("needs result", self.check(p))

    def test_folder_and_filename(self):
        p = self.write(self.tpath("human", "T-0004"),
                       ticket_text("T-0004", "author@t", "expert@t"))
        self.assertIn("lives in human/", self.check(p))
        p = self.write(self.tpath("expert@t", "T-0005"),
                       ticket_text("T-0006", "author@t", "expert@t"))
        self.assertIn("does not match the file name", self.check(p))

    def test_extra_section_reported(self):
        text = ticket_text("T-0007", "author@t", "expert@t").replace(
            "## Result", "## Notes\n\nx\n\n## Result")
        p = self.write(self.tpath("expert@t", "T-0007"), text)
        self.assertIn("sections must be exactly", self.check(p))

    def test_frontmatter_error_reported(self):
        p = self.write(self.tpath("expert@t", "T-0008"), "---\nid: [unterminated\n---\n")
        self.assertIn("frontmatter", self.check(p))

    def test_direct_agent_edit_is_reported(self):
        p = self.write(self.tpath("expert@t", "T-0009"),
                       ticket_text("T-0009", "author@t", "expert@t"))
        reason = self.check(p, "author:math-writer")
        self.assertIn("only through the academy MCP tools", reason)
        self.assertIn("author:math-writer", reason)

    def test_invalid_packet_reported(self):
        good = self.write(os.path.join(self.board, "packets", "author@t",
                                       "P-0001-fixture.md"), packet_text("P-0001", "author@t"))
        self.assertIsNone(self.check(good))
        bad = self.write(os.path.join(self.board, "packets", "author@t", "P-0002-bad.md"),
                         packet_text("P-0002", "author@t").replace("## Evidence", "## Evid"))
        self.assertIn("missing section", self.check(bad))


@unittest.skipUnless(HAVE_GIT, "git is not on PATH")
class TicketOwnershipTests(TicketEditCheckTests):
    """Field ownership against the board's git HEAD."""

    def committed_ticket(self, tid="T-0010", **kw):
        self.init_board_repo()
        p = self.write(self.tpath("expert@t", tid),
                       ticket_text(tid, "author@t", "expert@t", **kw))
        self.commit_all()
        return p

    def edit(self, path, **changes):
        with open(path, "r", encoding="utf-8") as fh:
            meta, body = ac.read_frontmatter(fh.read())
        thread = changes.pop("_thread", None)
        body_fn = changes.pop("_body", None)
        meta.update(changes)
        if thread:
            body = ac.append_thread(body, thread[0], thread[1], date="2026-09-28")
        if body_fn:
            body = body_fn(body)
        self.write(path, ac.write_frontmatter(meta, body))

    def test_sender_may_not_accept(self):
        p = self.committed_ticket()
        self.edit(p, status="accepted")
        reason = self.check(p, "author:math-writer", cwd=self.author_home)
        self.assertIn("status open -> accepted", reason)
        self.assertIn("receiver", reason)

    def test_receiver_may_accept(self):
        p = self.committed_ticket()
        self.edit(p, status="accepted",
                  _thread=("expert@t/review-chair", "status open -> accepted"))
        reason = self.check(p, "expert:review-chair", cwd=self.expert_home)
        self.assertIn("only through the academy MCP tools", reason)
        self.assertNotIn("status open", reason)
        self.assertNotIn("owned by", reason)

    def test_sender_may_not_write_result(self):
        p = self.committed_ticket()
        self.edit(p, result="done by me")
        self.assertIn("result is owned by the receiver",
                      self.check(p, "author:math-writer", cwd=self.author_home))

    def test_receiver_may_not_change_the_ask(self):
        p = self.committed_ticket()
        self.edit(p, ask="Something else.",
                  _body=lambda b: b.replace("Check it.", "Something else."))
        reason = self.check(p, "expert:review-chair", cwd=self.expert_home)
        self.assertIn("ask is owned by the sender", reason)
        self.assertIn("## Ask is owned by the sender", reason)

    def test_to_and_system_fields(self):
        p = self.committed_ticket()
        self.edit(p, to="human", created="2026-01-01")
        reason = self.check(p, "author:math-writer", cwd=self.author_home)
        self.assertIn("to may be changed only by the human", reason)
        self.assertIn("created is written by the server only", reason)

    def test_agent_outside_any_home(self):
        p = self.committed_ticket()
        self.edit(p, priority="high")
        self.assertIn("priority is owned by the sender",
                      self.check(p, "author:math-writer", cwd=self.outside))

    def test_cancel_needs_a_reason(self):
        p = self.committed_ticket()
        self.edit(p, status="cancelled")
        self.assertIn("needs a reason line",
                      self.check(p, "author:math-writer", cwd=self.author_home))

    def test_human_may_change_any_field(self):
        p = self.committed_ticket()
        self.edit(p, priority="high", result="noted", status="accepted",
                  ask="Reworded.")
        self.assertIsNone(self.check(p))

    def test_thread_is_append_only_for_the_human_too(self):
        p = self.committed_ticket()
        self.edit(p, _body=lambda b: b.replace("human: opened", "human: rewritten"))
        self.assertIn("append-only", self.check(p))

    def test_new_ticket_by_human_is_only_linted(self):
        self.init_board_repo()
        self.write(os.path.join(self.board, "README.md"), "board\n")
        self.commit_all()
        p = self.write(self.tpath("expert@t", "T-0011"),
                       ticket_text("T-0011", "author@t", "expert@t"))
        self.assertIsNone(self.check(p, tool="Write"))


# ---------------------------------------------------------------------------
# session_start
# ---------------------------------------------------------------------------

class SessionStartTests(Fixture):
    def start(self, cwd, env=None):
        e = dict(self.env)
        e.update(env or {})
        event = {"hook_event_name": "SessionStart", "source": "startup", "cwd": cwd}
        rc, out, err = run_hook("session_start.py", event, e)
        self.assertEqual(rc, 0, err)
        if out is None:
            return None
        self.assertEqual(out["hookSpecificOutput"]["hookEventName"], "SessionStart")
        return out["hookSpecificOutput"]["additionalContext"]

    def populate(self):
        b = self.board
        self.write(os.path.join(b, "author@t", "T-0001-a.md"),
                   ticket_text("T-0001", "expert@t", "author@t"))
        self.write(os.path.join(b, "author@t", "T-0002-b.md"),
                   ticket_text("T-0002", "human", "author@t", status="in-progress"))
        self.write(os.path.join(b, "author@t", "T-0003-c.md"),
                   ticket_text("T-0003", "expert@t", "author@t", status="closed",
                               result="done"))
        self.write(os.path.join(b, "author@t", "T-0004-d.md"),
                   ticket_text("T-0004", "expert@t", "author@t", status="blocked",
                               waiting_on=["T-0012"]))
        self.write(os.path.join(b, "expert@t", "T-0012-e.md"),
                   ticket_text("T-0012", "author@t", "expert@t", status="closed",
                               result="done"))
        self.write(os.path.join(b, "expert@t", "T-0013-f.md"),
                   ticket_text("T-0013", "author@t", "expert@t"))
        self.write(os.path.join(b, "human", "RESUME.md"), "free\n")
        self.write(os.path.join(b, "packets", "expert@t", "P-0001-x.md"),
                   packet_text("P-0001", "expert@t"))
        self.write(os.path.join(b, "packets", "author@t", "P-0007-y.md"),
                   packet_text("P-0007", "author@t", state="decided"))

    def test_silent_outside_a_home(self):
        self.populate()
        self.assertIsNone(self.start(self.outside))

    def test_status_line(self):
        self.populate()
        line = self.start(self.author_home)
        self.assertEqual(line, "academy: author@t — 2 open tickets to you, "
                               "1 packet awaiting Roey; freed: T-0004")
        self.assertNotIn("\n", line)
        cards = os.path.join(self.expert_home, "cards")
        os.makedirs(cards)
        line = self.start(cards)                            # a subdirectory of the home
        self.assertEqual(line, "academy: expert@t — 1 open ticket to you, "
                               "1 packet awaiting Roey")

    def test_relay_parent_freed_by_a_delivered_child(self):
        b = self.board
        self.write(os.path.join(b, "expert@t", "T-0030-p.md"),
                   ticket_text("T-0030", "author@t", "expert@t", status="blocked",
                               kind="research", final_to="researcher",
                               waiting_on=["T-0031"]))
        self.write(os.path.join(b, "researcher@t", "T-0031-c.md"),
                   ticket_text("T-0031", "expert@t", "researcher@t", status="delivered",
                               kind="research", final_to="researcher", parent="T-0030",
                               result="done"))
        self.write(os.path.join(b, "expert@t", "T-0032-q.md"),     # not a relay parent
                   ticket_text("T-0032", "author@t", "expert@t", status="blocked",
                               waiting_on=["T-0031"]))
        line = self.start(self.expert_home)
        self.assertTrue(line.endswith("; freed: T-0030"), line)

    def github_board(self, factory="transport"):
        """Switch the fixture workspace to the GitHub backend, its issues being the current
        file tickets (seeded into a MemoryTransport by a factory module on PYTHONPATH), and
        return the env for the hook."""
        sys.path.insert(0, SCRIPTS)
        import board_codec as bc
        issues = [bc.encode(m, b) for _r, m, b in ac.FileBoardStore(self.board).iter_tickets()]
        mods = os.path.join(self.tmp, "mods")
        fixture = self.write(os.path.join(mods, "issues.json"), json.dumps(issues))
        self.write(os.path.join(mods, "fake_gh_board.py"),
                   "import json, board_store as bs\n"
                   "def transport(cfg):\n"
                   "    t = bs.MemoryTransport()\n"
                   "    for e in json.load(open(cfg['fixture'], encoding='utf-8')):\n"
                   "        t.add_encoded(e)\n"
                   "    return t\n"
                   "def broken(cfg):\n"
                   "    raise RuntimeError('gh api: HTTP 401 Bad credentials')\n")
        with open(self.ws_path, encoding="utf-8") as fh:
            ws = json.load(fh)
        ws["board"] = {"path": ws["board"], "backend": "github", "repo": "o/r",
                       "transport": "fake_gh_board:" + factory, "fixture": fixture}
        self.write(self.ws_path, json.dumps(ws))
        return {"PYTHONPATH": os.pathsep.join([mods, os.path.join(PLUGIN, "lib")])}

    def test_status_line_on_the_github_backend_reads_the_issues(self):
        """The ticket files of a GitHub board are the frozen snapshot: the counts come from
        the issues, so a ticket file removed after the switch changes nothing."""
        self.populate()
        env = self.github_board()
        os.remove(os.path.join(self.board, "author@t", "T-0001-a.md"))
        os.remove(os.path.join(self.board, "author@t", "T-0002-b.md"))
        line = self.start(self.author_home, env)
        self.assertEqual(line, "academy: author@t — 2 open tickets to you, "
                               "1 packet awaiting Roey; freed: T-0004")

    def test_status_line_when_github_is_unreachable(self):
        self.populate()
        env = self.github_board("broken")
        line = self.start(self.author_home, env)
        self.assertTrue(line.startswith("academy: author@t — tickets not read: GitHub board "
                                        "unreachable (gh api: HTTP 401 Bad credentials)"), line)
        self.assertTrue(line.endswith("; 1 packet awaiting Roey"), line)

    def test_ids_reconciled(self):
        self.populate()
        self.write(os.path.join(self.board, ".ids", "next-packet"), "3\n")
        self.start(self.author_home)
        ids = os.path.join(self.board, ".ids")
        with open(os.path.join(ids, "next-ticket"), encoding="utf-8") as fh:
            self.assertEqual(fh.read(), "14\n")
        with open(os.path.join(ids, "next-packet"), encoding="utf-8") as fh:
            self.assertEqual(fh.read(), "8\n")
        self.write(os.path.join(ids, "next-ticket"), "40\n")   # never lowered
        self.start(self.author_home)
        with open(os.path.join(ids, "next-ticket"), encoding="utf-8") as fh:
            self.assertEqual(fh.read(), "40\n")
        self.assertFalse(os.path.exists(os.path.join(ids, "lock")))

    def test_empty_board(self):
        self.assertEqual(self.start(self.author_home),
                         "academy: author@t — 0 open tickets to you, "
                         "0 packets awaiting Roey")

    def test_decisions_waiting_line(self):
        self.write(os.path.join(self.board, "human", "T-0020-x.md"),
                   ticket_text("T-0020", "expert@t", "human"))
        self.write(os.path.join(self.board, "expert@t", "T-0021-y.md"),
                   ticket_text("T-0021", "author@t", "expert@t", status="blocked",
                               waiting_on=["human"]))
        body = ("\n## Summary\n\nA fixture.\n\n## Produced\n\nNothing.\n\n"
               "## Established vs assumed\n\nNothing.\n\n## Evidence\n\nNone.\n\n"
               "## Decisions needed\n\n### D1. Proceed?\n\n- (a) Yes.\n- (b) No.\n"
               "- Recommendation: (a), it is safe.\n\n## Machine notes\n\nNone.\n\n"
               "## Decision\n\n")
        meta = {"packet": "P-0099", "title": "Fixture P-0099", "instance": "expert@t",
               "kind": "other", "by": "expert@t", "state": "open", "created": "2026-09-27"}
        self.write(os.path.join(self.board, "packets", "expert@t", "P-0099-z.md"),
                   ac.write_frontmatter(meta, body))
        line = self.start(self.author_home)
        self.assertIn("3 decisions waiting — /academy:decide", line)

    def test_missing_board(self):
        shutil.rmtree(self.board)
        self.assertIn("not found", self.start(self.author_home))

    def test_invalid_config(self):
        cfg = config_for("author", "author@t", ns="paper")
        del cfg["paths"]["bib"]
        self.write(os.path.join(self.author_home, ".claude", "academy.json"), json.dumps(cfg))
        line = self.start(self.author_home)
        self.assertTrue(line.startswith("academy: author@t — invalid"), line)
        self.assertIn("paths.bib", line)
        self.write(os.path.join(self.author_home, ".claude", "academy.json"), "{not json")
        self.assertIn("invalid", self.start(self.author_home))

    def test_disagreement_with_workspace(self):
        cfg = config_for("author", "author@t", ns="paper")
        cfg["domains"] = ["other-domain"]
        self.write(os.path.join(self.author_home, ".claude", "academy.json"), json.dumps(cfg))
        line = self.start(self.author_home)
        self.assertIn("; config: domains differs", line)
        cfg = config_for("author", "author@nowhere", ns="paper")
        self.write(os.path.join(self.author_home, ".claude", "academy.json"), json.dumps(cfg))
        self.assertIn("author@nowhere is not an instance", self.start(self.author_home))

    @unittest.skipUnless(HAVE_GIT, "git is not on PATH")
    def test_board_commit(self):
        self.init_board_repo()
        self.write(os.path.join(self.board, "README.md"), "board\n")
        self.commit_all()
        self.populate()
        self.start(self.author_home, {"ACADEMY_BOARD_COMMIT": "1"})
        self.assertEqual(self.git("status", "--porcelain").strip(), "")
        msg = self.git("log", "-1", "--format=%B")
        self.assertTrue(msg.startswith("board: "), msg)
        self.assertIn("change(s)", msg)
        self.assertIn("Co-Authored-By:", msg)
        count = self.git("rev-list", "--count", "HEAD").strip()
        self.start(self.author_home, {"ACADEMY_BOARD_COMMIT": "1"})   # nothing new
        self.assertEqual(self.git("rev-list", "--count", "HEAD").strip(), count)

    @unittest.skipUnless(HAVE_GIT, "git is not on PATH")
    def test_board_commit_can_be_disabled(self):
        self.init_board_repo()
        self.populate()
        self.start(self.author_home)                        # ACADEMY_BOARD_COMMIT=0
        self.assertNotEqual(self.git("status", "--porcelain").strip(), "")


PY_LAUNCH = '"${ACADEMY_PYTHON:-$(command -v py || command -v python3)}" '


class HooksJsonTests(unittest.TestCase):
    def test_mcp_server_command_falls_back(self):
        with open(os.path.join(PLUGIN, ".mcp.json"), encoding="utf-8") as fh:
            server = json.load(fh)["mcpServers"]["academy"]
        # no shell there: $ACADEMY_PYTHON (Claude Code expands ${VAR:-default}), else py
        self.assertEqual(server["command"], "${ACADEMY_PYTHON:-py}")

    def test_hook_launcher_runs_without_py(self):
        import shutil
        import subprocess
        sh, py3 = shutil.which("sh"), shutil.which("python3") or sys.executable
        if not sh or os.name == "nt":
            self.skipTest("needs a POSIX sh")
        tmp = tempfile.mkdtemp(prefix="academy-launch-")
        try:
            os.makedirs(os.path.join(tmp, "bin"))
            os.makedirs(os.path.join(tmp, "plug", "scripts"))
            os.symlink(py3, os.path.join(tmp, "bin", "python3"))
            with open(os.path.join(tmp, "plug", "scripts", "x.py"), "w") as fh:
                fh.write("import sys; print(sys.stdin.read().upper())\n")
            cmd = PY_LAUNCH + '"${CLAUDE_PLUGIN_ROOT}/scripts/x.py"'
            env = {"PATH": os.path.join(tmp, "bin"), "CLAUDE_PLUGIN_ROOT": os.path.join(tmp, "plug")}
            out = subprocess.run([sh, "-c", cmd], input="event", capture_output=True,
                                 text=True, env=env, timeout=60)
            self.assertEqual((out.returncode, out.stdout.strip()), (0, "EVENT"), out.stderr)
        finally:
            shutil.rmtree(tmp, ignore_errors=True)

    def test_hooks_json(self):
        with open(os.path.join(PLUGIN, "hooks", "hooks.json"), encoding="utf-8") as fh:
            hooks = json.load(fh)["hooks"]
        cmds = {}
        for event, groups in hooks.items():
            for g in groups:
                for h in g["hooks"]:
                    # the interpreter: $ACADEMY_PYTHON, else py, else python3 (bash, which
                    # Claude Code runs hooks in on every platform, Git Bash on Windows)
                    self.assertTrue(h["command"].startswith(PY_LAUNCH + '"${CLAUDE_PLUGIN_ROOT}/'
                                                            'scripts/'), h["command"])
                    script = h["command"].split("/scripts/")[1].rstrip('"')
                    self.assertTrue(os.path.isfile(os.path.join(SCRIPTS, script)), script)
                    cmds[script] = (event, g.get("matcher"))
        self.assertEqual(cmds, {
            "session_start.py": ("SessionStart", None),
            "mcp_write_gate.py": ("PreToolUse", "mcp__.*academy.*"),
            "generated_view_guard.py": ("PreToolUse", "Edit|Write|MultiEdit|Bash|PowerShell"),
            "explainer_write_guard.py": ("PreToolUse", "Edit|Write|MultiEdit|NotebookEdit"),
            "ticket_edit_check.py": ("PostToolUse", "Edit|Write|MultiEdit"),
            "error_ledger.py": ("PostToolUseFailure", None),
        })

    def test_scripts_import_the_vendored_copy(self):
        for name in ("session_start.py", "mcp_write_gate.py", "generated_view_guard.py",
                     "ticket_edit_check.py", "explainer_write_guard.py"):
            with open(os.path.join(SCRIPTS, name), encoding="utf-8") as fh:
                text = fh.read()
            self.assertIn("import _academy as ac", text, name)
            self.assertNotIn("academy_common", text, name)


if __name__ == "__main__":
    unittest.main()
