"""Shared helpers for the Expert plugin's scripts (plan sections 3.4, 5, 8).

Nothing here re-implements the base plugin. It locates and imports:

* the vendored lib ``_academy.py`` (= ``academy/lib/academy_common.py``);
* the MCP server's library module (``academy/mcp/tools/library.py``), so quote
  normalisation and index parsing are the exact code ``library_verify_quote``
  and ``library_missing`` run;
* the MCP server's claims module, for ``check_grounds`` (tests only);
* the base plugin's ``packets.py`` / ``board.py``, for hook-landed packets.

The academy repo root comes from ``_academy.repo_root()`` (``$ACADEMY_ROOT`` wins,
symlinks resolved), and the base plugin is ``<root>/academy``
(``$ACADEMY_PLUGIN`` overrides it).
"""

import importlib.util
import json
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
PLUGIN = os.path.dirname(HERE)
if HERE not in sys.path:
    sys.path.insert(0, HERE)

import _academy as ac  # noqa: E402

GENERATED = "<!-- generated by academy: %s; do not edit -->"


# ----------------------------------------------------------------------------
# The base plugin and its modules
# ----------------------------------------------------------------------------

def academy_plugin():
    """The base plugin directory (``<academy repo>/academy``)."""
    env = os.environ.get("ACADEMY_PLUGIN")
    if env:
        return os.path.abspath(env)
    return os.path.join(ac.repo_root(), "academy")


_CACHE = {}


def _mcp_package():
    """Import ``<academy>/mcp/tools`` as the package ``academy_mcp_tools``."""
    if "pkg" in _CACHE:
        return _CACHE["pkg"]
    base = academy_plugin()
    lib = os.path.join(base, "lib")
    if lib not in sys.path:
        sys.path.insert(0, lib)          # tools/*.py import academy_common
    tools_dir = os.path.join(base, "mcp", "tools")
    init = os.path.join(tools_dir, "__init__.py")
    if not os.path.isfile(init):
        raise ImportError("academy MCP tools not found at %s" % tools_dir)
    spec = importlib.util.spec_from_file_location(
        "academy_mcp_tools", init, submodule_search_locations=[tools_dir])
    mod = importlib.util.module_from_spec(spec)
    sys.modules["academy_mcp_tools"] = mod
    spec.loader.exec_module(mod)
    _CACHE["pkg"] = mod
    return mod


def mcp_module(name):
    """``academy/mcp/tools/<name>.py`` (e.g. ``library``, ``claims``)."""
    key = "mod:" + name
    if key not in _CACHE:
        _mcp_package()
        __import__("academy_mcp_tools." + name)
        _CACHE[key] = sys.modules["academy_mcp_tools." + name]
    return _CACHE[key]


def library():
    """The MCP library module: ``find_quote``, ``normalise_quote``, ``parse_index`` ..."""
    return mcp_module("library")


def base_script(name):
    """Import one of the base plugin's scripts (``packets``, ``board``)."""
    key = "script:" + name
    if key not in _CACHE:
        sdir = os.path.join(academy_plugin(), "scripts")
        for p in (os.path.join(academy_plugin(), "lib"), sdir):
            if p not in sys.path:
                sys.path.insert(0, p)
        __import__(name)
        _CACHE[key] = sys.modules[name]
    return _CACHE[key]


# ----------------------------------------------------------------------------
# Instances and homes
# ----------------------------------------------------------------------------

def load_workspace_or_none(path=None):
    try:
        return ac.load_workspace(path)
    except ac.AcademyError:
        return None


def expert_instances(workspace, domain=None):
    """Expert instance names, those serving ``domain`` first."""
    out = [n for n, i in sorted(workspace.get("instances", {}).items())
           if i.get("role") == "expert"]
    if domain:
        out.sort(key=lambda n: domain not in workspace["instances"][n].get("domains", []))
    return out


def expert_home(workspace=None, home=None, domain=None):
    """The library home: ``home`` if given, else the first Expert instance's home."""
    if home:
        return os.path.abspath(home)
    ws = workspace or load_workspace_or_none()
    if not ws:
        return None
    names = expert_instances(ws, domain)
    if not names:
        return None
    return os.path.abspath(ws["instances"][names[0]]["home"])


def expert_instance_for_home(workspace, home):
    name = ac.instance_for_home(workspace, home) if workspace else None
    return name if name and name.startswith("expert@") else None


def expert_config(home):
    """``load_config(home)`` for an Expert home, or None (missing/invalid/other role)."""
    try:
        cfg = ac.load_config(home)
    except ac.AcademyError:
        return None
    return cfg if cfg.get("role") == "expert" else None


def home_path(home, cfg, key, default):
    """A single-path ``paths.<key>`` of the Expert config, absolute."""
    val = ((cfg or {}).get("paths") or {}).get(key) or default
    if isinstance(val, list):
        val = val[0]
    return os.path.join(home, val)


def is_under(path, root):
    """True when ``path`` lies at or under ``root`` (case-insensitive on Windows)."""
    if not path or not root:
        return False
    return ac._rel_to(root, path) is not None


# ----------------------------------------------------------------------------
# Hook events
# ----------------------------------------------------------------------------

def _text_of(content):
    if isinstance(content, str):
        return content
    if isinstance(content, list):
        parts = []
        for c in content:
            if isinstance(c, dict) and c.get("type") == "text":
                parts.append(c.get("text") or "")
            elif isinstance(c, str):
                parts.append(c)
        return "\n".join(parts)
    return ""


def last_message_from_transcript(path):
    """The text of the last assistant message in a JSONL transcript, or ''."""
    if not path or not os.path.isfile(path):
        return ""
    last = ""
    try:
        with open(path, "r", encoding="utf-8", errors="replace") as fh:
            for line in fh:
                line = line.strip()
                if not line:
                    continue
                try:
                    rec = json.loads(line)
                except ValueError:
                    continue
                msg = rec.get("message") if isinstance(rec, dict) else None
                role = (msg or {}).get("role") or rec.get("type")
                if role != "assistant":
                    continue
                text = _text_of((msg or {}).get("content"))
                if text.strip():
                    last = text
    except OSError:
        return ""
    return last


def final_message(event):
    """A finished subagent's final text: ``last_assistant_message`` if the event
    carries it, else the last assistant text of ``agent_transcript_path``."""
    for key in ("last_assistant_message", "lastAssistantMessage"):
        v = event.get(key)
        text = _text_of(v) if not isinstance(v, str) else v
        if text and text.strip():
            return text
    return last_message_from_transcript(
        event.get("agent_transcript_path") or event.get("agentTranscriptPath"))


def is_expert_agent(event, bare):
    """The event's agent is ``bare`` shipped by this plugin (``expert:<bare>``) or bare."""
    ns, name = ac.agent_identity(event)
    return name == bare and ns in ("", "expert")


def slug_id(cid):
    """A registry id as one path segment: ``lem:strip-bound`` -> ``lem-strip-bound``."""
    s = "".join(c if (c.isalnum() or c in "-_.") else "-" for c in str(cid))
    while "--" in s:
        s = s.replace("--", "-")
    return s.strip("-.") or "item"


def utf8_stdout():
    try:
        sys.stdout.reconfigure(encoding="utf-8")
    except (AttributeError, ValueError):
        pass
