"""ledger_views.py -- rebuild an author's ledgers as generated views from the library's records.

    py ledger_views.py [--home H] [--instance author@bi] [--out DIR] [--check DIR]

After ``ledger_split.py`` (plan section 6, phase 7) the truth of BI's three ledgers
lives in the library home: cards (``cards/<key>/*.md``), the related-work files
(``ledgers/<instance>/``) and the review records (``reviews/<ns>/<id>/<pass>/``).
Each ledger's ``ledgers/<instance>/_manifest-<name>.json`` records the order: the
records' verbatim pieces and the headings between them. This script concatenates
them again, so that each view is the old ledger, byte for byte, below one marker
line (``generated by academy``; ``generated_view_guard`` refuses hand edits).

Records added after the migration, which no manifest names, are appended under
``## Added after the migration``: a card as its pinpoint, status and quote, a review
pass as its two run lines and outcome.

``--out`` (default ``<home>/views/<instance>``) receives ``sources.md``,
``related_work.md`` and ``verdicts.md``. ``--check DIR`` compares the rebuilt text
(without the marker line) with the ledgers in DIR and exits 1 on any difference.
"""

import argparse
import json
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
if HERE not in sys.path:
    sys.path.insert(0, HERE)

import _expert as ex  # noqa: E402
from _expert import ac  # noqa: E402
import cards as cardlib  # noqa: E402
import ledger_split as ls  # noqa: E402

GENERATOR = "expert/scripts/ledger_views.py"
NAMES = ("sources", "related_work", "verdicts")


def load_manifest(home, instance, name):
    p = ls.manifest_path(home, instance, name)
    if not os.path.isfile(p):
        return None
    with open(p, "r", encoding="utf-8") as fh:
        return json.load(fh)


def _referenced(manifest):
    out = set()
    for s in manifest["segments"]:
        for k in ("card", "file"):
            if k in s:
                out.add(s[k])
    return out


def added_cards(home, manifest):
    """Cards on disk that the sources manifest does not name, rendered briefly."""
    seen = _referenced(manifest)
    lines = []
    for p in cardlib.iter_cards(home):
        rel = os.path.relpath(p, home).replace("\\", "/")
        if rel in seen:
            continue
        try:
            meta, body = cardlib.read_card(p)
        except (OSError, ac.AcademyError, UnicodeDecodeError):
            lines.append("- `%s`: unreadable" % rel)
            continue
        q = cardlib.quote_text(cardlib.sections(body).get("## Quote", ""))
        lines.append("- **%s, %s** (%s; read from %s; %s) `%s`%s" % (
            meta.get("key"), meta.get("pinpoint"), meta.get("version"),
            meta.get("read_from"), meta.get("status") or "status unset", rel,
            (": \"%s\"" % q) if q and not q.startswith("_No verbatim") else ""))
    return lines


def added_reviews(home, manifest):
    """Review passes on disk that the verdicts manifest does not name."""
    seen = _referenced(manifest)
    root = ex.home_path(home, ex.expert_config(home), "reviews", "reviews")
    lines = []
    if not os.path.isdir(root):
        return lines
    for dp, _dn, fn in sorted(os.walk(root)):
        runs = [f for f in sorted(fn) if f[:1] in "AB" and f.endswith(".md")]
        if not runs:
            continue
        rels = [os.path.relpath(os.path.join(dp, f), home).replace("\\", "/") for f in runs]
        if any(r in seen for r in rels):
            continue
        head = os.path.relpath(dp, root).replace("\\", "/")
        lines += ["", "### %s" % head, ""]
        for f, rel in zip(runs, rels):
            try:
                with open(os.path.join(dp, f), "r", encoding="utf-8") as fh:
                    meta, _b = ac.read_frontmatter(fh.read())
            except (OSError, ac.AcademyError, UnicodeDecodeError):
                lines.append("- `%s`: unreadable" % rel)
                continue
            lines.append("- run %s: %s / %s -- blocking: %s (`%s`)" % (
                meta.get("run"), meta.get("verdict"), meta.get("model"),
                meta.get("blocking") or "none", rel))
    return lines


def render(home, instance, name):
    man = load_manifest(home, instance, name)
    if man is None:
        return None, None
    body = ls.render_manifest(home, man)
    extra = []
    if name == "sources":
        extra = added_cards(home, man)
    elif name == "verdicts":
        extra = added_reviews(home, man)
    if extra:
        body = body.rstrip("\n") + "\n\n## Added after the migration\n\n" + \
            "\n".join(extra).strip("\n") + "\n"
    marker = ex.GENERATED % ("%s from ledgers/%s/_manifest-%s.json" % (GENERATOR, instance,
                                                                      name))
    return marker + "\n" + body, body


def main(argv=None):
    ex.utf8_stdout()
    ap = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    ap.add_argument("--home")
    ap.add_argument("--instance", default="author@bi")
    ap.add_argument("--out")
    ap.add_argument("--check", help="directory holding the original ledgers to compare")
    args = ap.parse_args(argv)
    home = ex.expert_home(home=args.home)
    if not home or not os.path.isdir(home):
        sys.stderr.write("ledger_views: no library home (pass --home)\n")
        return 2
    out = args.out or os.path.join(home, "views", args.instance)
    bad = 0
    for name in NAMES:
        text, body = render(home, args.instance, name)
        if text is None:
            print("%s: no manifest, skipped" % name)
            continue
        if args.check:
            p = os.path.join(args.check, name + ".md")
            with open(p, "r", encoding="utf-8", newline="") as fh:
                orig = fh.read().replace("\r\n", "\n")
            same = orig == body
            bad += not same
            print("%s: %s" % (name, "identical to %s" % p.replace("\\", "/") if same
                              else "DIFFERS from %s" % p.replace("\\", "/")))
            continue
        path = os.path.join(out, name + ".md")
        ac.atomic_write(path, text)
        print("wrote %s" % path.replace("\\", "/"))
    return 1 if bad else 0


if __name__ == "__main__":
    sys.exit(main())
