"""Schema-v2 records for the registry tests: the temp homes of ``_util.Homes`` as the
one-time R5 migration (``migrate_v2``, since moved out of the marketplace) left them,
plus four more Slope1-style claims. Generated once from that migration; edit as data."""

#: (home directory name, path inside it) -> file text
V2_FILES = {
    ('FlatSurfLab', 'claims/lab/foo.md'): '---\nid: lab:foo\nkind: claim\ntitle: a claim\nstatus: supported\nbears_on: [paper:prop:foo]\nlifecycle: active\ndomain: translation-surfaces\nwhere: experiments/x.py\nopen:\n  - no audit\nevidence:\n  - experiment | results/x.json | not audited | - | 0 counterexamples below 10\nhistory:\n  - 2026-09-28 | supported | schema v2 migration (R5), status unchanged\n  - 2026-09-24 | supported | ran\n  - 2026-09-20 | open | created\n---\nBody.\n',
    ('FlatSurfLab', 'claims/lab/old.md'): '---\nid: lab:old\nkind: claim\ntitle: an abandoned claim\nstatus: supported\nlifecycle: dropped\ndomain: translation-surfaces\nwhere: experiments/x.py\nopen:\n  - nothing\nevidence: []\nhistory:\n  - "2026-09-28 | dropped | schema v2 migration (R5): lifecycle dropped; status = last recorded status `supported`"\n  - 2026-09-25 | dropped | out of scope\n  - 2026-09-20 | supported | ran once\n---\n',
    ('Slope1illuminationResearch', 'assumptions/GA-2T′.md'): '---\nid: GA-2T′\nkind: assumption\ntitle: primed\nlifecycle: active\ndomain: translation-surfaces\nold: (2T′)\nimplies: []\nincomparable_with: []\nevidence: []\nhistory:\n  - 2026-09-28 | | schema v2 migration (R5)\n---\n## Statement\nx\n',
    ('Slope1illuminationResearch', 'claims/CEX-1.md'): '---\nid: CEX-1\nkind: claim\nform: prop\ntitle: t\nstatus: refuted\nlifecycle: active\naliases: [N8]\ndomain: translation-surfaces\nsummary: s\nevidence:\n  - verdict | computation/verdicts/2026-09-24_G8.md | - | 2026-09-24_G8 | names this record as subject\nhistory:\n  - "2026-09-28 | refuted | schema v2 migration (R5): Disproved -> refuted"\n---\n## Statement\nIt fails.\n',
    ('Slope1illuminationResearch', 'claims/CRIT-1.md'): '---\nid: CRIT-1\nkind: claim\nform: prop\ntitle: reduced one\nstatus: proved-modulo\nmodulo:\n  - OPEN-2\ndepends_on: []\nlifecycle: active\naliases: [R2 Prop 9.9]\ndomain: translation-surfaces\ntags: [t]\nsummary: It is Reduced to OPEN-2.\nstatus_note: Reduced (to OPEN-2)\nsource: here\nadded: 2026-09-24\nevidence: []\nhistory:\n  - "2026-09-28 | proved-modulo | schema v2 migration (R5): Reduced -> proved-modulo; modulo = the reduction target(s) named by id"\n  - 2026-09-25 | | relabelled, with a continuation line.\n  - 2026-09-24 | | created\n---\n\n## Statement\n\nThe statement is **Reduced** to OPEN-2.\n',
    ('Slope1illuminationResearch', 'claims/OBS-1.md'): '---\nid: OBS-1\nkind: claim\nform: draft\ntitle: a draft\nstatus: sketch\ndepends_on: [OPEN-2]\nlifecycle: active\naliases: []\ndomain: translation-surfaces\ntags: []\nsummary: s\nsource: here\nadded: 2026-09-24\nevidence: []\nhistory:\n  - "2026-09-28 | sketch | schema v2 migration (R5): Not settled, statement with a ## Proof -> sketch"\n---\n\n## Statement\n\nX.\n\n## Proof\n\nBecause.\n',
    ('Slope1illuminationResearch', 'claims/OPEN-2.md'): '---\nid: OPEN-2\nkind: question\nform: open\ntitle: an open problem\nstatus: open\ndepends_on: []\nlifecycle: active\naliases: []\ndomain: translation-surfaces\ntags: []\nsummary: s\nsource: here\nadded: 2026-09-24\nevidence: []\nhistory:\n  - "2026-09-28 | open | schema v2 migration (R5): Not settled, open problem/question -> open"\n---\n\n## Statement\n\nIs it?\n',
    ('Slope1illuminationResearch', 'claims/OPEN-7.md'): '---\nid: OPEN-7\nkind: question\nform: open\ntitle: partly done\nstatus: open\ndepends_on: []\nlifecycle: active\naliases: []\ndomain: translation-surfaces\ntags: []\nsummary: s\nsource: here\nadded: 2026-09-24\nevidence: []\nhistory:\n  - "2026-09-28 | open | schema v2 migration (R5): Partial -> open parent + sketch cases (split)"\n---\n\n## Statement\n\nSome cases are known.\n',
}
